"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import abc
from typing import Optional

from friendli.core.container_audio import AsyncContainerAudio, SyncContainerAudio
from friendli.core.container_chat import AsyncContainerChat, SyncContainerChat
from friendli.core.container_classification import (
    AsyncContainerClassification,
    SyncContainerClassification,
)
from friendli.core.container_completions import (
    AsyncContainerCompletions,
    SyncContainerCompletions,
)
from friendli.core.container_image import AsyncContainerImage, SyncContainerImage
from friendli.core.container_messages import (
    AsyncContainerMessages,
    SyncContainerMessages,
)
from friendli.core.container_responses import (
    AsyncContainerResponses,
    SyncContainerResponses,
)
from friendli.core.container_token import AsyncContainerToken, SyncContainerToken

from .basesdk import AsyncSDK, BaseSDK, SyncSDK
from .sdkconfiguration import SDKConfiguration


class BaseContainer(BaseSDK):
    def __init__(
        self, sdk_config: SDKConfiguration, parent_ref: object | None = None
    ) -> None:
        BaseSDK.__init__(self, sdk_config, parent_ref=parent_ref)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self) -> None: ...


class SyncContainer(BaseContainer, SyncSDK):
    chat: SyncContainerChat
    responses: SyncContainerResponses
    messages: SyncContainerMessages
    completions: SyncContainerCompletions
    token: SyncContainerToken
    image: SyncContainerImage
    audio: SyncContainerAudio
    classification: SyncContainerClassification

    def _init_sdks(self):
        self.chat = SyncContainerChat(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.responses = SyncContainerResponses(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.messages = SyncContainerMessages(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.completions = SyncContainerCompletions(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.token = SyncContainerToken(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.image = SyncContainerImage(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.audio = SyncContainerAudio(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.classification = SyncContainerClassification(
            self.sdk_configuration, parent_ref=self.parent_ref
        )


class AsyncContainer(BaseContainer, AsyncSDK):
    chat: AsyncContainerChat
    responses: AsyncContainerResponses
    messages: AsyncContainerMessages
    completions: AsyncContainerCompletions
    token: AsyncContainerToken
    image: AsyncContainerImage
    audio: AsyncContainerAudio
    classification: AsyncContainerClassification

    def _init_sdks(self):
        self.chat = AsyncContainerChat(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.responses = AsyncContainerResponses(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.messages = AsyncContainerMessages(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.completions = AsyncContainerCompletions(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.token = AsyncContainerToken(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.image = AsyncContainerImage(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.audio = AsyncContainerAudio(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.classification = AsyncContainerClassification(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
