"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK, SyncSDK, AsyncSDK
from friendli.core import models, utils
from friendli.core._hooks import HookContext
from friendli.core.types import OptionalNullable, UNSET
from friendli.core.utils import get_security_from_env
from friendli.core.utils.unmarshal_json_response import unmarshal_json_response
from typing import Iterable, List, Mapping, Optional, Union
import abc


class BaseContainerClassification(BaseSDK):
    pass


class SyncContainerClassification(BaseContainerClassification, SyncSDK):
    def classify(
        self,
        *,
        model: OptionalNullable[str] = UNSET,
        input_: OptionalNullable[
            Union[
                models.ContainerTextClassificationBodyInput,
                models.ContainerTextClassificationBodyInputTypedDict,
            ]
        ] = UNSET,
        tokens: OptionalNullable[Iterable[int]] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ContainerTextClassificationSuccess:
        """Text classification

        Given a text input, the model classifies it into categories.

        :param model: Routes the request to a specific adapter.
        :param input: Input text to classify, encoded as a string or array of strings. To classify multiple inputs in a single request, pass an array of strings.

            Either `input` or `tokens` field is required.
        :param tokens: The tokenized prompt (i.e., input tokens).

            Either `input` or `tokens` field is required.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.CONTAINER_TEXT_CLASSIFICATION_OP_SERVERS[0]
        request = models.ContainerTextClassificationBody(
            model=model,
            input=utils.unmarshal(
                input_, OptionalNullable[models.ContainerTextClassificationBodyInput]
            ),
            tokens=utils.unmarshal(tokens, OptionalNullable[List[int]]),
        )
        req = self._build_request(
            method="POST",
            path="/classify",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.ContainerTextClassificationBody
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="containerTextClassification",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["SyncContainer.Classification"],
                extensions={
                    "x-mint": {
                        "content": "Given a text input, the model classifies it into categories.",
                        "href": "/openapi/container/text-classification",
                        "metadata": {
                            "description": "Classify text into categories using Friendli Container. Run text classification models on your own infrastructure with full data control and privacy.",
                            "og:description": "Classify text into categories using Friendli Container. Run text classification models on your own infrastructure with full data control and privacy.",
                            "og:title": "SyncContainer Text Classification",
                            "sidebarTitle": "Text Classification",
                            "title": "SyncContainer Text Classification",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.ContainerTextClassificationSuccess, http_res
            )
        if utils.match_response(http_res, ["422", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        raise models.SDKError("Unexpected response received", http_res)


class AsyncContainerClassification(BaseContainerClassification, AsyncSDK):
    async def classify(
        self,
        *,
        model: OptionalNullable[str] = UNSET,
        input_: OptionalNullable[
            Union[
                models.ContainerTextClassificationBodyInput,
                models.ContainerTextClassificationBodyInputTypedDict,
            ]
        ] = UNSET,
        tokens: OptionalNullable[Iterable[int]] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ContainerTextClassificationSuccess:
        """Text classification

        Given a text input, the model classifies it into categories.

        :param model: Routes the request to a specific adapter.
        :param input: Input text to classify, encoded as a string or array of strings. To classify multiple inputs in a single request, pass an array of strings.

            Either `input` or `tokens` field is required.
        :param tokens: The tokenized prompt (i.e., input tokens).

            Either `input` or `tokens` field is required.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.CONTAINER_TEXT_CLASSIFICATION_OP_SERVERS[0]
        request = models.ContainerTextClassificationBody(
            model=model,
            input=utils.unmarshal(
                input_, OptionalNullable[models.ContainerTextClassificationBodyInput]
            ),
            tokens=utils.unmarshal(tokens, OptionalNullable[List[int]]),
        )
        req = self._build_request_async(
            method="POST",
            path="/classify",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.ContainerTextClassificationBody
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="containerTextClassification",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["AsyncContainer.Classification"],
                extensions={
                    "x-mint": {
                        "content": "Given a text input, the model classifies it into categories.",
                        "href": "/openapi/container/text-classification",
                        "metadata": {
                            "description": "Classify text into categories using Friendli Container. Run text classification models on your own infrastructure with full data control and privacy.",
                            "og:description": "Classify text into categories using Friendli Container. Run text classification models on your own infrastructure with full data control and privacy.",
                            "og:title": "AsyncContainer Text Classification",
                            "sidebarTitle": "Text Classification",
                            "title": "AsyncContainer Text Classification",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.ContainerTextClassificationSuccess, http_res
            )
        if utils.match_response(http_res, ["422", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        raise models.SDKError("Unexpected response received", http_res)
