"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK, SyncSDK, AsyncSDK
from datetime import datetime
from friendli.core import models, utils
from friendli.core._hooks import HookContext
from friendli.core.types import OptionalNullable, UNSET
from friendli.core.utils import get_security_from_env
from friendli.core.utils.unmarshal_json_response import unmarshal_json_response
from typing import Mapping, Optional
import abc


class BaseCost(BaseSDK):
    pass


class SyncCost(BaseCost, SyncSDK):
    def get_cost(
        self,
        *,
        start_time: datetime,
        end_time: datetime,
        bucket_width: OptionalNullable[models.CostBucketWidth] = UNSET,
        limit: OptionalNullable[int] = UNSET,
        page: OptionalNullable[str] = UNSET,
        group_by: OptionalNullable[models.CostGroupBy] = UNSET,
        x_friendli_team: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.CostResponse:
        """Get cost details for the team.

        :param start_time: RFC 3339 timestamp in UTC. The time portion must be zeroed out (e.g., 2026-01-01T00:00:00Z). Must be no earlier than one year ago.
        :param end_time: RFC 3339 timestamp in UTC. The time portion must be zeroed out (e.g., 2026-01-02T00:00:00Z).
        :param bucket_width: Width of each time bucket in response. Currently only `1d` is supported, default to `1d`.
        :param limit: A limit on the number of buckets to be returned. Limit can range between 1 and 35, and the default is 7.
        :param page: A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.
        :param group_by: Group the costs by the specified fields. Currently only `line_item` is supported.
        :param x_friendli_team: ID of team to run requests as (optional parameter).
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        request = models.GetCostRequest(
            start_time=start_time,
            bucket_width=bucket_width,
            end_time=end_time,
            limit=limit,
            page=page,
            group_by=group_by,
            x_friendli_team=x_friendli_team,
        )
        req = self._build_request(
            method="GET",
            path="/v1/team/cost",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getCost",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["SyncCost"],
                extensions={
                    "x-mint": {
                        "content": "Get cost details for the team.\n\nIf `X-Friendli-Team` is omitted, this endpoint uses the default team configured in Friendli Suite.\n\nThere may be a slight delay between usage and when it shows up in cost. If you need to call this endpoint repeatedly, wait at least 5 minutes between calls.\n\nTo request successfully, it is mandatory to enter a **Personal API Key** (e.g. flp_XXX) value in the **Bearer Token** field.\nRefer to the [authentication section](/openapi/introduction#authentication) on our introduction page to learn how to acquire this variable and [visit here](https://friendli.ai/suite/~/setting/keys) to generate your API Key.",
                        "href": "/openapi/administration/usage/cost",
                        "metadata": {
                            "description": "Get cost details for the team.",
                            "og:description": "Get cost details for the team.",
                            "og:title": "SyncCost",
                            "sidebarTitle": "SyncCost",
                            "title": "SyncCost",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.CostResponse, http_res)
        if utils.match_response(http_res, ["422", "429", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        raise models.SDKError("Unexpected response received", http_res)


class AsyncCost(BaseCost, AsyncSDK):
    async def get_cost(
        self,
        *,
        start_time: datetime,
        end_time: datetime,
        bucket_width: OptionalNullable[models.CostBucketWidth] = UNSET,
        limit: OptionalNullable[int] = UNSET,
        page: OptionalNullable[str] = UNSET,
        group_by: OptionalNullable[models.CostGroupBy] = UNSET,
        x_friendli_team: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.CostResponse:
        """Get cost details for the team.

        :param start_time: RFC 3339 timestamp in UTC. The time portion must be zeroed out (e.g., 2026-01-01T00:00:00Z). Must be no earlier than one year ago.
        :param end_time: RFC 3339 timestamp in UTC. The time portion must be zeroed out (e.g., 2026-01-02T00:00:00Z).
        :param bucket_width: Width of each time bucket in response. Currently only `1d` is supported, default to `1d`.
        :param limit: A limit on the number of buckets to be returned. Limit can range between 1 and 35, and the default is 7.
        :param page: A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.
        :param group_by: Group the costs by the specified fields. Currently only `line_item` is supported.
        :param x_friendli_team: ID of team to run requests as (optional parameter).
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        request = models.GetCostRequest(
            start_time=start_time,
            bucket_width=bucket_width,
            end_time=end_time,
            limit=limit,
            page=page,
            group_by=group_by,
            x_friendli_team=x_friendli_team,
        )
        req = self._build_request_async(
            method="GET",
            path="/v1/team/cost",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getCost",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["AsyncCost"],
                extensions={
                    "x-mint": {
                        "content": "Get cost details for the team.\n\nIf `X-Friendli-Team` is omitted, this endpoint uses the default team configured in Friendli Suite.\n\nThere may be a slight delay between usage and when it shows up in cost. If you need to call this endpoint repeatedly, wait at least 5 minutes between calls.\n\nTo request successfully, it is mandatory to enter a **Personal API Key** (e.g. flp_XXX) value in the **Bearer Token** field.\nRefer to the [authentication section](/openapi/introduction#authentication) on our introduction page to learn how to acquire this variable and [visit here](https://friendli.ai/suite/~/setting/keys) to generate your API Key.",
                        "href": "/openapi/administration/usage/cost",
                        "metadata": {
                            "description": "Get cost details for the team.",
                            "og:description": "Get cost details for the team.",
                            "og:title": "AsyncCost",
                            "sidebarTitle": "AsyncCost",
                            "title": "AsyncCost",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.CostResponse, http_res)
        if utils.match_response(http_res, ["422", "429", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        raise models.SDKError("Unexpected response received", http_res)
