"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import abc
from collections.abc import Iterable, Mapping
from typing import List, Optional, Union

from friendli.core import models, utils
from friendli.core._hooks import HookContext
from friendli.core.types import UNSET, OptionalNullable
from friendli.core.utils import get_security_from_env
from friendli.core.utils.unmarshal_json_response import unmarshal_json_response

from .basesdk import AsyncSDK, BaseSDK, SyncSDK


class BaseDedicatedClassification(BaseSDK):
    pass


class SyncDedicatedClassification(BaseDedicatedClassification, SyncSDK):
    def classify(
        self,
        *,
        model: str,
        x_friendli_team: OptionalNullable[str] = UNSET,
        input_: OptionalNullable[
            models.DedicatedTextClassificationBodyInput
            | models.DedicatedTextClassificationBodyInputTypedDict
        ] = UNSET,
        tokens: OptionalNullable[Iterable[int]] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.DedicatedTextClassificationSuccess:
        """Text classification

        Classify text input into categories with per-class probabilities.

        :param model: ID of target endpoint. If you want to send request to specific adapter, use the format \\"YOUR_ENDPOINT_ID:YOUR_ADAPTER_ROUTE\\". Otherwise, you can just use \\"YOUR_ENDPOINT_ID\\" alone.
        :param x_friendli_team: ID of team to run requests as (optional parameter).
        :param input: Input text to classify, encoded as a string or array of strings. To classify multiple inputs in a single request, pass an array of strings.

            Either `input` or `tokens` field is required.
        :param tokens: The tokenized prompt (i.e., input tokens).

            Either `input` or `tokens` field is required.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        request = models.DedicatedTextClassificationRequest(
            x_friendli_team=x_friendli_team,
            dedicated_text_classification_body=models.DedicatedTextClassificationBody(
                model=model,
                input=utils.unmarshal(
                    input_,
                    OptionalNullable[models.DedicatedTextClassificationBodyInput],
                ),
                tokens=utils.unmarshal(tokens, OptionalNullable[list[int]]),
            ),
        )
        req = self._build_request(
            method="POST",
            path="/dedicated/classify",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.dedicated_text_classification_body,
                False,
                False,
                "json",
                models.DedicatedTextClassificationBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="dedicatedTextClassification",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["SyncDedicated.Classification"],
                extensions={
                    "x-mint": {
                        "content": "Classify text input into categories with per-class probabilities.\n\nTo request successfully, it is mandatory to enter a **Personal API Key** (e.g. flp_XXX) value in the **Bearer Token** field.\nRefer to the [authentication section](/openapi/introduction#authentication) on our introduction page to learn how to acquire this variable and [visit here](https://friendli.ai/suite/~/setting/keys) to generate your API Key.",
                        "href": "/openapi/dedicated/inference/text-classification",
                        "metadata": {
                            "description": "Classify text input into categories with per-class probabilities.",
                            "og:description": "Classify text input into categories with per-class probabilities.",
                            "og:title": "SyncDedicated Text Classification",
                            "sidebarTitle": "Text Classification",
                            "title": "SyncDedicated Text Classification",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.DedicatedTextClassificationSuccess, http_res
            )
        if utils.match_response(http_res, ["422", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        raise models.SDKError("Unexpected response received", http_res)


class AsyncDedicatedClassification(BaseDedicatedClassification, AsyncSDK):
    async def classify(
        self,
        *,
        model: str,
        x_friendli_team: OptionalNullable[str] = UNSET,
        input_: OptionalNullable[
            models.DedicatedTextClassificationBodyInput
            | models.DedicatedTextClassificationBodyInputTypedDict
        ] = UNSET,
        tokens: OptionalNullable[Iterable[int]] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models.DedicatedTextClassificationSuccess:
        """Text classification

        Classify text input into categories with per-class probabilities.

        :param model: ID of target endpoint. If you want to send request to specific adapter, use the format \\"YOUR_ENDPOINT_ID:YOUR_ADAPTER_ROUTE\\". Otherwise, you can just use \\"YOUR_ENDPOINT_ID\\" alone.
        :param x_friendli_team: ID of team to run requests as (optional parameter).
        :param input: Input text to classify, encoded as a string or array of strings. To classify multiple inputs in a single request, pass an array of strings.

            Either `input` or `tokens` field is required.
        :param tokens: The tokenized prompt (i.e., input tokens).

            Either `input` or `tokens` field is required.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        request = models.DedicatedTextClassificationRequest(
            x_friendli_team=x_friendli_team,
            dedicated_text_classification_body=models.DedicatedTextClassificationBody(
                model=model,
                input=utils.unmarshal(
                    input_,
                    OptionalNullable[models.DedicatedTextClassificationBodyInput],
                ),
                tokens=utils.unmarshal(tokens, OptionalNullable[list[int]]),
            ),
        )
        req = self._build_request_async(
            method="POST",
            path="/dedicated/classify",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.dedicated_text_classification_body,
                False,
                False,
                "json",
                models.DedicatedTextClassificationBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="dedicatedTextClassification",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["AsyncDedicated.Classification"],
                extensions={
                    "x-mint": {
                        "content": "Classify text input into categories with per-class probabilities.\n\nTo request successfully, it is mandatory to enter a **Personal API Key** (e.g. flp_XXX) value in the **Bearer Token** field.\nRefer to the [authentication section](/openapi/introduction#authentication) on our introduction page to learn how to acquire this variable and [visit here](https://friendli.ai/suite/~/setting/keys) to generate your API Key.",
                        "href": "/openapi/dedicated/inference/text-classification",
                        "metadata": {
                            "description": "Classify text input into categories with per-class probabilities.",
                            "og:description": "Classify text input into categories with per-class probabilities.",
                            "og:title": "AsyncDedicated Text Classification",
                            "sidebarTitle": "Text Classification",
                            "title": "AsyncDedicated Text Classification",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.DedicatedTextClassificationSuccess, http_res
            )
        if utils.match_response(http_res, ["422", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        raise models.SDKError("Unexpected response received", http_res)
