"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import abc
from collections.abc import Mapping
from typing import Optional

from friendli.core import models as models_
from friendli.core import utils
from friendli.core._hooks import HookContext
from friendli.core.types import UNSET, OptionalNullable
from friendli.core.utils import get_security_from_env
from friendli.core.utils.unmarshal_json_response import unmarshal_json_response

from .basesdk import AsyncSDK, BaseSDK, SyncSDK


class BaseModel(BaseSDK):
    pass


class SyncModel(BaseModel, SyncSDK):
    def models(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models_.ServerlessModelListSuccess:
        """List Models

        Lists the currently available models, and provides basic information about each one such as pricing and functionality.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request(
            method="GET",
            path="/serverless/v1/models",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="serverlessModels",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["SyncServerless.Model"],
                extensions={
                    "x-mint": {
                        "content": "Lists the currently available models, and provides basic information about each one such as pricing and functionality.\n\nSee available models at [this pricing table](/guides/model-apis/pricing).",
                        "href": "/openapi/model-apis/models",
                        "metadata": {
                            "description": "Lists the currently available models, and provides basic information about each one such as pricing and functionality.",
                            "og:description": "Lists the currently available models, and provides basic information about each one such as pricing and functionality.",
                            "og:title": "SyncModel APIs Supported SyncModels",
                            "sidebarTitle": "List Models",
                            "tag": "Beta",
                            "title": "SyncModel APIs Supported SyncModels",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.ServerlessModelListSuccess, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.SDKError("API error occurred", http_res, http_res_text)
        raise models_.SDKError("Unexpected response received", http_res)


class AsyncModel(BaseModel, AsyncSDK):
    async def models(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models_.ServerlessModelListSuccess:
        """List Models

        Lists the currently available models, and provides basic information about each one such as pricing and functionality.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request_async(
            method="GET",
            path="/serverless/v1/models",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="serverlessModels",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["AsyncServerless.Model"],
                extensions={
                    "x-mint": {
                        "content": "Lists the currently available models, and provides basic information about each one such as pricing and functionality.\n\nSee available models at [this pricing table](/guides/model-apis/pricing).",
                        "href": "/openapi/model-apis/models",
                        "metadata": {
                            "description": "Lists the currently available models, and provides basic information about each one such as pricing and functionality.",
                            "og:description": "Lists the currently available models, and provides basic information about each one such as pricing and functionality.",
                            "og:title": "AsyncModel APIs Supported AsyncModels",
                            "sidebarTitle": "List Models",
                            "tag": "Beta",
                            "title": "AsyncModel APIs Supported AsyncModels",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.ServerlessModelListSuccess, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.SDKError("API error occurred", http_res, http_res_text)
        raise models_.SDKError("Unexpected response received", http_res)
