"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Dict, Optional, Tuple, Union

from pydantic import Field

from friendli.core import models
from friendli.core.types import UNSET, OptionalNullable

from ._version import (
    __gen_version__,
    __openapi_doc_version__,
    __user_agent__,
    __version__,
)
from .httpclient import AsyncHttpClient, HttpClient
from .utils import Logger, RetryConfig, remove_suffix

SERVERS = ["https://api.friendli.ai"]
"Contains the list of servers available to the SDK"


@dataclass
class SDKConfiguration:
    client: HttpClient | None
    client_supplied: bool
    async_client: AsyncHttpClient | None
    async_client_supplied: bool
    debug_logger: Logger
    security: models.Security | Callable[[], models.Security] | None = None
    server_url: str | None = ""
    server_idx: int | None = 0
    language: str = "python"
    openapi_doc_version: str = __openapi_doc_version__
    sdk_version: str = __version__
    gen_version: str = __gen_version__
    user_agent: str = __user_agent__
    retry_config: OptionalNullable[RetryConfig] = Field(default_factory=lambda: UNSET)
    timeout_ms: int | None = None

    def get_server_details(self) -> tuple[str, dict[str, str]]:
        if self.server_url is not None and self.server_url:
            return (remove_suffix(self.server_url, "/"), {})
        if self.server_idx is None:
            self.server_idx = 0
        return (SERVERS[self.server_idx], {})
