"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK, SyncSDK, AsyncSDK
from friendli.core import models, utils
from friendli.core._hooks import HookContext
from friendli.core.types import OptionalNullable, UNSET
from friendli.core.utils import get_security_from_env
from friendli.core.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Dict, Iterable, List, Mapping, Optional, Union
import abc


class BaseServerlessMessages(BaseSDK):
    pass


class SyncServerlessMessages(BaseServerlessMessages, SyncSDK):
    def messages(
        self,
        *,
        messages: Union[
            Iterable[models.MessagesInputMessage],
            Iterable[models.MessagesInputMessageTypedDict],
        ],
        model: str,
        x_friendli_team: OptionalNullable[str] = UNSET,
        max_tokens: OptionalNullable[int] = UNSET,
        system: OptionalNullable[
            Union[
                models.ServerlessMessagesBodySystem,
                models.ServerlessMessagesBodySystemTypedDict,
            ]
        ] = UNSET,
        stream: OptionalNullable[bool] = UNSET,
        temperature: OptionalNullable[float] = UNSET,
        top_p: OptionalNullable[float] = UNSET,
        top_k: OptionalNullable[int] = UNSET,
        stop_sequences: OptionalNullable[Iterable[str]] = UNSET,
        tools: OptionalNullable[
            Union[
                Iterable[models.MessagesToolDefinition],
                Iterable[models.MessagesToolDefinitionTypedDict],
            ]
        ] = UNSET,
        tool_choice: OptionalNullable[
            Union[models.MessagesToolChoice, models.MessagesToolChoiceTypedDict]
        ] = UNSET,
        thinking: OptionalNullable[
            Union[models.MessagesThinkingConfig, models.MessagesThinkingConfigTypedDict]
        ] = UNSET,
        output_config: OptionalNullable[
            Union[models.MessagesOutputConfig, models.MessagesOutputConfigTypedDict]
        ] = UNSET,
        cache_control: OptionalNullable[Mapping[str, Any]] = UNSET,
        container: OptionalNullable[Mapping[str, Any]] = UNSET,
        context_manager: OptionalNullable[Mapping[str, Any]] = UNSET,
        inference_geo: OptionalNullable[Mapping[str, Any]] = UNSET,
        metadata: OptionalNullable[Mapping[str, Any]] = UNSET,
        service_tier: OptionalNullable[
            Union[
                models.ServerlessMessagesBodyServiceTier,
                models.ServerlessMessagesBodyServiceTierTypedDict,
            ]
        ] = UNSET,
        additional_properties: Optional[Mapping[str, Any]] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ServerlessMessagesSuccess:
        """Messages

        Generate responses using Anthropic Messages-style payloads.

        :param messages: A list of conversation messages ordered from oldest to newest. Must contain at least one item.
        :param model: Code of the model to use. See [available model list](https://friendli.ai/docs/guides/model-apis/pricing#billing-methods).
        :param x_friendli_team: ID of team to run requests as (optional parameter).
        :param max_tokens: Maximum number of tokens to generate for the assistant response. Must be greater than 0 when provided.
        :param system: Optional top-level system instruction applied before conversation turns. Supports a plain string or an array of text blocks.
        :param stream: Whether to stream output as server-sent events (`text/event-stream`). When false or omitted, returns a single JSON response.
        :param temperature: Sampling temperature. Lower values make outputs more deterministic; higher values increase diversity.
        :param top_p: Nucleus sampling parameter. The model samples from the smallest token set whose cumulative probability reaches `top_p`.
        :param top_k: Limits sampling to the `k` most likely tokens at each decoding step.
        :param stop_sequences: Stop strings that terminate generation when matched in output. The matched value is returned in `stop_sequence` when applicable.
        :param tools: Tool definitions available to the model. Use this to allow tool calls with structured arguments.
        :param tool_choice: Controls tool-calling behavior (`auto`, `any`, `tool`, `none`) and optional parallel-call behavior.
        :param thinking: Controls reasoning behavior with mode (`enabled`, `disabled`, `adaptive`). `enabled` requires `budget_tokens`; `disabled` and `adaptive` must not include it.
        :param output_config: Output generation options including effort level and structured output format settings.
        :param cache_control: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param container: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param context_manager: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param inference_geo: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param metadata: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param service_tier: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param additional_properties:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        request = models.ServerlessMessagesRequest(
            x_friendli_team=x_friendli_team,
            serverless_messages_body=models.ServerlessMessagesBody(
                messages=utils.get_pydantic_model(
                    messages, List[models.MessagesInputMessage]
                ),
                max_tokens=max_tokens,
                model=model,
                system=utils.get_pydantic_model(
                    system, OptionalNullable[models.ServerlessMessagesBodySystem]
                ),
                stream=stream,
                temperature=temperature,
                top_p=top_p,
                top_k=top_k,
                stop_sequences=utils.unmarshal(
                    stop_sequences, OptionalNullable[List[str]]
                ),
                tools=utils.get_pydantic_model(
                    tools, OptionalNullable[List[models.MessagesToolDefinition]]
                ),
                tool_choice=utils.get_pydantic_model(
                    tool_choice, OptionalNullable[models.MessagesToolChoice]
                ),
                thinking=utils.get_pydantic_model(
                    thinking, OptionalNullable[models.MessagesThinkingConfig]
                ),
                output_config=utils.get_pydantic_model(
                    output_config, OptionalNullable[models.MessagesOutputConfig]
                ),
                cache_control=utils.unmarshal(
                    cache_control, OptionalNullable[Dict[str, Any]]
                ),
                container=utils.unmarshal(container, OptionalNullable[Dict[str, Any]]),
                context_manager=utils.unmarshal(
                    context_manager, OptionalNullable[Dict[str, Any]]
                ),
                inference_geo=utils.unmarshal(
                    inference_geo, OptionalNullable[Dict[str, Any]]
                ),
                metadata=utils.unmarshal(metadata, OptionalNullable[Dict[str, Any]]),
                service_tier=utils.unmarshal(
                    service_tier,
                    OptionalNullable[models.ServerlessMessagesBodyServiceTier],
                ),
                **utils.unmarshal(additional_properties, Optional[Dict[str, Any]])
                or {},
            ),
        )
        req = self._build_request(
            method="POST",
            path="/serverless/v1/messages",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.serverless_messages_body,
                False,
                False,
                "json",
                models.ServerlessMessagesBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="serverlessMessages",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["SyncServerless.Messages"],
                extensions={
                    "x-mint": {
                        "content": "Send Anthropic Messages-style JSON.\nDetailed request/response field descriptions are provided in the OpenAPI schema below on this page.\n\nSee available models at [this pricing table](/guides/model-apis/pricing#billing-methods).\n\n<Note>\nThe Messages API may not be supported by all models available on Model APIs.\n</Note>\n\nTo request successfully, it is mandatory to enter a **Personal API Key** (e.g. flp_XXX) value in the **Bearer Token** field.\nRefer to the [authentication section](/openapi/introduction#authentication) on our introduction page to learn how to acquire this variable and [visit here](https://friendli.ai/suite/~/setting/keys) to generate your API Key.\n\nWhen streaming mode is used (i.e., `stream` option is set to `true`), the response is in MIME type `text/event-stream`. Otherwise, the content type is `application/json`.\nYou can view the schema of the streamed sequence of chunk objects in streaming mode [here](/openapi/model-apis/messages-chunk-object).\n\n<Warning>Server-side tools are not supported in the Messages API. In `tools`, only custom/client function tools are used; non-`custom` tool types are ignored.</Warning>\n\n<Info>\nThis API is currently in **Beta**.\nWhile we strive to provide a stable and reliable experience, this feature is still under active development.\nAs a result, you may encounter unexpected behavior or limitations.\nWe encourage you to provide feedback to help us improve the feature before its official release.\n\n- [Feature request & feedback](mailto:support@friendli.ai)\n- [Contact support](mailto:support@friendli.ai)\n\n</Info>",
                        "href": "/openapi/model-apis/messages",
                        "metadata": {
                            "description": "Use the Anthropic Messages-style API on Friendli Model APIs. Send structured message payloads and receive assistant responses.",
                            "og:description": "Use the Anthropic Messages-style API on Friendli Model APIs. Send structured message payloads and receive assistant responses.",
                            "og:title": "Model APIs Messages",
                            "sidebarTitle": "Messages",
                            "tag": "Beta",
                            "title": "Model APIs Messages",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ServerlessMessagesSuccess, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                models.MessagesErrorResponseData, http_res
            )
            raise models.MessagesErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        raise models.SDKError("Unexpected response received", http_res)


class AsyncServerlessMessages(BaseServerlessMessages, AsyncSDK):
    async def messages(
        self,
        *,
        messages: Union[
            Iterable[models.MessagesInputMessage],
            Iterable[models.MessagesInputMessageTypedDict],
        ],
        model: str,
        x_friendli_team: OptionalNullable[str] = UNSET,
        max_tokens: OptionalNullable[int] = UNSET,
        system: OptionalNullable[
            Union[
                models.ServerlessMessagesBodySystem,
                models.ServerlessMessagesBodySystemTypedDict,
            ]
        ] = UNSET,
        stream: OptionalNullable[bool] = UNSET,
        temperature: OptionalNullable[float] = UNSET,
        top_p: OptionalNullable[float] = UNSET,
        top_k: OptionalNullable[int] = UNSET,
        stop_sequences: OptionalNullable[Iterable[str]] = UNSET,
        tools: OptionalNullable[
            Union[
                Iterable[models.MessagesToolDefinition],
                Iterable[models.MessagesToolDefinitionTypedDict],
            ]
        ] = UNSET,
        tool_choice: OptionalNullable[
            Union[models.MessagesToolChoice, models.MessagesToolChoiceTypedDict]
        ] = UNSET,
        thinking: OptionalNullable[
            Union[models.MessagesThinkingConfig, models.MessagesThinkingConfigTypedDict]
        ] = UNSET,
        output_config: OptionalNullable[
            Union[models.MessagesOutputConfig, models.MessagesOutputConfigTypedDict]
        ] = UNSET,
        cache_control: OptionalNullable[Mapping[str, Any]] = UNSET,
        container: OptionalNullable[Mapping[str, Any]] = UNSET,
        context_manager: OptionalNullable[Mapping[str, Any]] = UNSET,
        inference_geo: OptionalNullable[Mapping[str, Any]] = UNSET,
        metadata: OptionalNullable[Mapping[str, Any]] = UNSET,
        service_tier: OptionalNullable[
            Union[
                models.ServerlessMessagesBodyServiceTier,
                models.ServerlessMessagesBodyServiceTierTypedDict,
            ]
        ] = UNSET,
        additional_properties: Optional[Mapping[str, Any]] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ServerlessMessagesSuccess:
        """Messages

        Generate responses using Anthropic Messages-style payloads.

        :param messages: A list of conversation messages ordered from oldest to newest. Must contain at least one item.
        :param model: Code of the model to use. See [available model list](https://friendli.ai/docs/guides/model-apis/pricing#billing-methods).
        :param x_friendli_team: ID of team to run requests as (optional parameter).
        :param max_tokens: Maximum number of tokens to generate for the assistant response. Must be greater than 0 when provided.
        :param system: Optional top-level system instruction applied before conversation turns. Supports a plain string or an array of text blocks.
        :param stream: Whether to stream output as server-sent events (`text/event-stream`). When false or omitted, returns a single JSON response.
        :param temperature: Sampling temperature. Lower values make outputs more deterministic; higher values increase diversity.
        :param top_p: Nucleus sampling parameter. The model samples from the smallest token set whose cumulative probability reaches `top_p`.
        :param top_k: Limits sampling to the `k` most likely tokens at each decoding step.
        :param stop_sequences: Stop strings that terminate generation when matched in output. The matched value is returned in `stop_sequence` when applicable.
        :param tools: Tool definitions available to the model. Use this to allow tool calls with structured arguments.
        :param tool_choice: Controls tool-calling behavior (`auto`, `any`, `tool`, `none`) and optional parallel-call behavior.
        :param thinking: Controls reasoning behavior with mode (`enabled`, `disabled`, `adaptive`). `enabled` requires `budget_tokens`; `disabled` and `adaptive` must not include it.
        :param output_config: Output generation options including effort level and structured output format settings.
        :param cache_control: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param container: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param context_manager: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param inference_geo: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param metadata: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param service_tier: Compatibility field accepted for request portability. Parsed but not used for generation.
        :param additional_properties:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        request = models.ServerlessMessagesRequest(
            x_friendli_team=x_friendli_team,
            serverless_messages_body=models.ServerlessMessagesBody(
                messages=utils.get_pydantic_model(
                    messages, List[models.MessagesInputMessage]
                ),
                max_tokens=max_tokens,
                model=model,
                system=utils.get_pydantic_model(
                    system, OptionalNullable[models.ServerlessMessagesBodySystem]
                ),
                stream=stream,
                temperature=temperature,
                top_p=top_p,
                top_k=top_k,
                stop_sequences=utils.unmarshal(
                    stop_sequences, OptionalNullable[List[str]]
                ),
                tools=utils.get_pydantic_model(
                    tools, OptionalNullable[List[models.MessagesToolDefinition]]
                ),
                tool_choice=utils.get_pydantic_model(
                    tool_choice, OptionalNullable[models.MessagesToolChoice]
                ),
                thinking=utils.get_pydantic_model(
                    thinking, OptionalNullable[models.MessagesThinkingConfig]
                ),
                output_config=utils.get_pydantic_model(
                    output_config, OptionalNullable[models.MessagesOutputConfig]
                ),
                cache_control=utils.unmarshal(
                    cache_control, OptionalNullable[Dict[str, Any]]
                ),
                container=utils.unmarshal(container, OptionalNullable[Dict[str, Any]]),
                context_manager=utils.unmarshal(
                    context_manager, OptionalNullable[Dict[str, Any]]
                ),
                inference_geo=utils.unmarshal(
                    inference_geo, OptionalNullable[Dict[str, Any]]
                ),
                metadata=utils.unmarshal(metadata, OptionalNullable[Dict[str, Any]]),
                service_tier=utils.unmarshal(
                    service_tier,
                    OptionalNullable[models.ServerlessMessagesBodyServiceTier],
                ),
                **utils.unmarshal(additional_properties, Optional[Dict[str, Any]])
                or {},
            ),
        )
        req = self._build_request_async(
            method="POST",
            path="/serverless/v1/messages",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.serverless_messages_body,
                False,
                False,
                "json",
                models.ServerlessMessagesBody,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="serverlessMessages",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=["AsyncServerless.Messages"],
                extensions={
                    "x-mint": {
                        "content": "Send Anthropic Messages-style JSON.\nDetailed request/response field descriptions are provided in the OpenAPI schema below on this page.\n\nSee available models at [this pricing table](/guides/model-apis/pricing#billing-methods).\n\n<Note>\nThe Messages API may not be supported by all models available on Model APIs.\n</Note>\n\nTo request successfully, it is mandatory to enter a **Personal API Key** (e.g. flp_XXX) value in the **Bearer Token** field.\nRefer to the [authentication section](/openapi/introduction#authentication) on our introduction page to learn how to acquire this variable and [visit here](https://friendli.ai/suite/~/setting/keys) to generate your API Key.\n\nWhen streaming mode is used (i.e., `stream` option is set to `true`), the response is in MIME type `text/event-stream`. Otherwise, the content type is `application/json`.\nYou can view the schema of the streamed sequence of chunk objects in streaming mode [here](/openapi/model-apis/messages-chunk-object).\n\n<Warning>Server-side tools are not supported in the Messages API. In `tools`, only custom/client function tools are used; non-`custom` tool types are ignored.</Warning>\n\n<Info>\nThis API is currently in **Beta**.\nWhile we strive to provide a stable and reliable experience, this feature is still under active development.\nAs a result, you may encounter unexpected behavior or limitations.\nWe encourage you to provide feedback to help us improve the feature before its official release.\n\n- [Feature request & feedback](mailto:support@friendli.ai)\n- [Contact support](mailto:support@friendli.ai)\n\n</Info>",
                        "href": "/openapi/model-apis/messages",
                        "metadata": {
                            "description": "Use the Anthropic Messages-style API on Friendli Model APIs. Send structured message payloads and receive assistant responses.",
                            "og:description": "Use the Anthropic Messages-style API on Friendli Model APIs. Send structured message payloads and receive assistant responses.",
                            "og:title": "Model APIs Messages",
                            "sidebarTitle": "Messages",
                            "tag": "Beta",
                            "title": "Model APIs Messages",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ServerlessMessagesSuccess, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                models.MessagesErrorResponseData, http_res
            )
            raise models.MessagesErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.SDKError("API error occurred", http_res, http_res_text)
        raise models.SDKError("Unexpected response received", http_res)
