"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import abc
from collections.abc import Iterable, Mapping
from datetime import datetime
from typing import List, Optional

from friendli.core import models as models_
from friendli.core import utils
from friendli.core._hooks import HookContext
from friendli.core.types import UNSET, OptionalNullable
from friendli.core.utils import get_security_from_env
from friendli.core.utils.unmarshal_json_response import unmarshal_json_response

from .basesdk import AsyncSDK, BaseSDK, SyncSDK


class BaseUsage(BaseSDK):
    pass


class SyncUsage(BaseUsage, SyncSDK):
    def get_usage(
        self,
        *,
        start_time: datetime,
        end_time: datetime,
        bucket_width: OptionalNullable[models_.UsageBucketWidth] = UNSET,
        limit: OptionalNullable[int] = UNSET,
        page: OptionalNullable[str] = UNSET,
        group_by: OptionalNullable[Iterable[models_.UsageGroupBy]] = UNSET,
        models: OptionalNullable[Iterable[str]] = UNSET,
        user_ids: OptionalNullable[Iterable[str]] = UNSET,
        product_types: OptionalNullable[Iterable[models_.ProductType]] = UNSET,
        gpu_types: OptionalNullable[Iterable[str]] = UNSET,
        x_friendli_team: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models_.UsageResponse:
        """Get usage details for the team.

        :param start_time: RFC 3339 timestamp in UTC. Must fall on a 5-minute boundary (e.g., 2026-01-01T10:05:00Z). It must be no earlier than one year ago. When `bucket_width=1h`, it must align to an hour boundary (e.g., `10:00:00Z`); when `bucket_width=1d`, it must align to a day boundary (e.g., `00:00:00Z`).
        :param end_time: RFC 3339 timestamp in UTC. Must fall on a 5-minute boundary (e.g., 2026-01-01T10:05:00Z), and its minute value must match `start_time`'s. It must obey the same hour/day alignment as `start_time` when `bucket_width=1h` or `1d`.
        :param bucket_width: Width of each time bucket in response. Currently `1d`, `1h`, and `5m` are supported, default to `1d`.
        :param limit: Specifies the number of buckets to return.
            - `bucket_width=1d`: default limit = 7, max limit = 31
            - `bucket_width=1h`: default limit = 24, max limit = 168
            - `bucket_width=5m`: default limit = 12, max limit = 288
        :param page: A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.
        :param group_by: Group the usage by the specified fields. Support fields include `model`, `product_type`, `user_id` and any combination of them.
        :param models: Return only usage for the listed Model APIs and Dedicated Endpoints. Values are model IDs, endpoint IDs, or a mix.
        :param user_ids: Return only usage for these users.
        :param product_types: Return only usage for the specified product types. Supported fields include `model_apis`, `dedicated_endpoints` and any combination of them.
        :param gpu_types: Return only usage for the specified GPU types. When this filter is given, only 'gpu_usage' will be provided. Combining `gpu_types` with 'product_types=model_apis` is rejected with HTTP 400.
        :param x_friendli_team: ID of team to run requests as (optional parameter).
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        request = models_.GetUsageRequest(
            start_time=start_time,
            end_time=end_time,
            bucket_width=bucket_width,
            limit=limit,
            page=page,
            group_by=utils.unmarshal(
                group_by, OptionalNullable[list[models_.UsageGroupBy]]
            ),
            models=utils.unmarshal(models, OptionalNullable[list[str]]),
            user_ids=utils.unmarshal(user_ids, OptionalNullable[list[str]]),
            product_types=utils.unmarshal(
                product_types, OptionalNullable[list[models_.ProductType]]
            ),
            gpu_types=utils.unmarshal(gpu_types, OptionalNullable[list[str]]),
            x_friendli_team=x_friendli_team,
        )
        req = self._build_request(
            method="GET",
            path="/v1/team/usage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getUsage",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["SyncUsage"],
                extensions={
                    "x-mint": {
                        "content": "Get usage details for the team.\n\nIf `X-Friendli-Team` is omitted, this endpoint uses the default team configured in Friendli Suite.\n\nTo request successfully, it is mandatory to enter a **Personal API Key** (e.g. flp_XXX) value in the **Bearer Token** field.\nRefer to the [authentication section](/openapi/introduction#authentication) on our introduction page to learn how to acquire this variable and [visit here](https://friendli.ai/suite/~/setting/keys) to generate your API Key.",
                        "href": "/openapi/administration/usage",
                        "metadata": {
                            "description": "Get usage details for the team.",
                            "og:description": "Get usage details for the team.",
                            "og:title": "SyncUsage",
                            "sidebarTitle": "SyncUsage",
                            "title": "SyncUsage",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.UsageResponse, http_res)
        if utils.match_response(http_res, ["400", "422", "429", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models_.SDKError("API error occurred", http_res, http_res_text)
        raise models_.SDKError("Unexpected response received", http_res)


class AsyncUsage(BaseUsage, AsyncSDK):
    async def get_usage(
        self,
        *,
        start_time: datetime,
        end_time: datetime,
        bucket_width: OptionalNullable[models_.UsageBucketWidth] = UNSET,
        limit: OptionalNullable[int] = UNSET,
        page: OptionalNullable[str] = UNSET,
        group_by: OptionalNullable[Iterable[models_.UsageGroupBy]] = UNSET,
        models: OptionalNullable[Iterable[str]] = UNSET,
        user_ids: OptionalNullable[Iterable[str]] = UNSET,
        product_types: OptionalNullable[Iterable[models_.ProductType]] = UNSET,
        gpu_types: OptionalNullable[Iterable[str]] = UNSET,
        x_friendli_team: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: str | None = None,
        timeout_ms: int | None = None,
        http_headers: Mapping[str, str] | None = None,
    ) -> models_.UsageResponse:
        """Get usage details for the team.

        :param start_time: RFC 3339 timestamp in UTC. Must fall on a 5-minute boundary (e.g., 2026-01-01T10:05:00Z). It must be no earlier than one year ago. When `bucket_width=1h`, it must align to an hour boundary (e.g., `10:00:00Z`); when `bucket_width=1d`, it must align to a day boundary (e.g., `00:00:00Z`).
        :param end_time: RFC 3339 timestamp in UTC. Must fall on a 5-minute boundary (e.g., 2026-01-01T10:05:00Z), and its minute value must match `start_time`'s. It must obey the same hour/day alignment as `start_time` when `bucket_width=1h` or `1d`.
        :param bucket_width: Width of each time bucket in response. Currently `1d`, `1h`, and `5m` are supported, default to `1d`.
        :param limit: Specifies the number of buckets to return.
            - `bucket_width=1d`: default limit = 7, max limit = 31
            - `bucket_width=1h`: default limit = 24, max limit = 168
            - `bucket_width=5m`: default limit = 12, max limit = 288
        :param page: A cursor for use in pagination. Corresponding to the `next_page` field from the previous response.
        :param group_by: Group the usage by the specified fields. Support fields include `model`, `product_type`, `user_id` and any combination of them.
        :param models: Return only usage for the listed Model APIs and Dedicated Endpoints. Values are model IDs, endpoint IDs, or a mix.
        :param user_ids: Return only usage for these users.
        :param product_types: Return only usage for the specified product types. Supported fields include `model_apis`, `dedicated_endpoints` and any combination of them.
        :param gpu_types: Return only usage for the specified GPU types. When this filter is given, only 'gpu_usage' will be provided. Combining `gpu_types` with 'product_types=model_apis` is rejected with HTTP 400.
        :param x_friendli_team: ID of team to run requests as (optional parameter).
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        request = models_.GetUsageRequest(
            start_time=start_time,
            end_time=end_time,
            bucket_width=bucket_width,
            limit=limit,
            page=page,
            group_by=utils.unmarshal(
                group_by, OptionalNullable[list[models_.UsageGroupBy]]
            ),
            models=utils.unmarshal(models, OptionalNullable[list[str]]),
            user_ids=utils.unmarshal(user_ids, OptionalNullable[list[str]]),
            product_types=utils.unmarshal(
                product_types, OptionalNullable[list[models_.ProductType]]
            ),
            gpu_types=utils.unmarshal(gpu_types, OptionalNullable[list[str]]),
            x_friendli_team=x_friendli_team,
        )
        req = self._build_request_async(
            method="GET",
            path="/v1/team/usage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )
        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 60000, 1.5, 3600000), True
                )
        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])
        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getUsage",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models_.Security
                ),
                tags=["AsyncUsage"],
                extensions={
                    "x-mint": {
                        "content": "Get usage details for the team.\n\nIf `X-Friendli-Team` is omitted, this endpoint uses the default team configured in Friendli Suite.\n\nTo request successfully, it is mandatory to enter a **Personal API Key** (e.g. flp_XXX) value in the **Bearer Token** field.\nRefer to the [authentication section](/openapi/introduction#authentication) on our introduction page to learn how to acquire this variable and [visit here](https://friendli.ai/suite/~/setting/keys) to generate your API Key.",
                        "href": "/openapi/administration/usage",
                        "metadata": {
                            "description": "Get usage details for the team.",
                            "og:description": "Get usage details for the team.",
                            "og:title": "AsyncUsage",
                            "sidebarTitle": "AsyncUsage",
                            "title": "AsyncUsage",
                        },
                    }
                },
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models_.UsageResponse, http_res)
        if utils.match_response(http_res, ["400", "422", "429", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.SDKError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models_.SDKError("API error occurred", http_res, http_res_text)
        raise models_.SDKError("Unexpected response received", http_res)
