"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import base64
import io
from os import PathLike
from typing import IO, Any, Union
from pydantic.functional_validators import BeforeValidator
from typing_extensions import Annotated

Base64FileInput = Union[IO[bytes], PathLike[str]]


def encode_base64_file_input(value: Any) -> Any:
    """Convert PathLike or IO[bytes] inputs to a base64 string. All standard binary streams
    that inherit from io.IOBase are handled. Other values pass through.
    """
    if isinstance(value, (PathLike, io.IOBase)):
        if isinstance(value, PathLike):
            with open(value, "rb") as fh:
                binary = fh.read()
        else:
            position = value.tell() if value.seekable() else None
            binary = value.read()
            if position is not None:
                value.seek(position)
            if isinstance(binary, str):
                binary = binary.encode()
        if not isinstance(binary, (bytes, bytearray)):
            raise TypeError(
                f"Base64FileInput expected binary IO returning bytes; got {type(binary).__name__}"
            )
        return base64.b64encode(binary).decode("ascii")
    return value


Base64EncodedString = Annotated[str, BeforeValidator(encode_base64_file_input)]
