"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from friendli.core.types import BaseModel


class AcceleratorRequirementTypedDict(TypedDict):
    """Accelerator requirement."""

    type: str
    "Specifies the instance type."
    count: int
    "Specifies the number of instances."


class AcceleratorRequirement(BaseModel):
    """Accelerator requirement."""

    type: str
    "Specifies the instance type."
    count: int
    "Specifies the number of instances."
