"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from friendli.core.types import BaseModel


class AssistantMessageToolCallFunctionTypedDict(TypedDict):
    name: str
    "The name of function."
    arguments: str
    "The arguments of function in JSON schema format to call the function."


class AssistantMessageToolCallFunction(BaseModel):
    name: str
    "The name of function."
    arguments: str
    "The arguments of function in JSON schema format to call the function."
