"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .assistantmessagetoolcall import (
    AssistantMessageToolCall,
    AssistantMessageToolCallTypedDict,
)
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class AssistantMessageTypedDict(TypedDict):
    role: Literal["assistant"]
    "The role of the messages author."
    content: NotRequired[Nullable[str]]
    "The content of assistant message. Required unless `tool_calls` is specified."
    reasoning_content: NotRequired[Nullable[str]]
    "The intermediate reasoning content of assistant message."
    reasoning: NotRequired[Nullable[str]]
    "The intermediate reasoning content of assistant message. This field is a compatible option for the 'reasoning_content' field."
    name: NotRequired[Nullable[str]]
    "The name for the participant to distinguish between participants with the same role."
    tool_calls: NotRequired[Nullable[List[AssistantMessageToolCallTypedDict]]]


class AssistantMessage(BaseModel):
    ROLE: Annotated[
        Annotated[Literal["assistant"], AfterValidator(validate_const("assistant"))],
        pydantic.Field(alias="role"),
    ] = "assistant"
    "The role of the messages author."
    content: OptionalNullable[str] = UNSET
    "The content of assistant message. Required unless `tool_calls` is specified."
    reasoning_content: OptionalNullable[str] = UNSET
    "The intermediate reasoning content of assistant message."
    reasoning: OptionalNullable[str] = UNSET
    "The intermediate reasoning content of assistant message. This field is a compatible option for the 'reasoning_content' field."
    name: OptionalNullable[str] = UNSET
    "The name for the participant to distinguish between participants with the same role."
    tool_calls: OptionalNullable[List[AssistantMessageToolCall]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["content", "reasoning_content", "reasoning", "name", "tool_calls"]
        )
        nullable_fields = set(
            ["content", "reasoning_content", "reasoning", "name", "tool_calls"]
        )
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    AssistantMessage.model_rebuild()
except NameError:
    pass
