"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from friendli.core.types import BaseModel


class AudioTranscriptionInputTokenDetailsTypedDict(TypedDict):
    audio_tokens: int
    "Number of audio tokens billed for this request."
    text_tokens: int
    "Number of text tokens billed for this request."


class AudioTranscriptionInputTokenDetails(BaseModel):
    audio_tokens: int
    "Number of audio tokens billed for this request."
    text_tokens: int
    "Number of text tokens billed for this request."
