"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import List

from typing_extensions import TypedDict

from friendli.core.types import BaseModel


class BaseClassificationDataTypedDict(TypedDict):
    index: int
    "The index of the input in the list of inputs."
    label: str
    "The predicted label for the input text."
    num_classes: int
    "The number of possible labels the model can predict."
    probs: list[float]
    "A list of logits for each possible label."


class BaseClassificationData(BaseModel):
    index: int
    "The index of the input in the list of inputs."
    label: str
    "The predicted label for the input text."
    num_classes: int
    "The number of possible labels the model can predict."
    probs: list[float]
    "A list of logits for each possible label."
