"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

import io
from typing import IO, Annotated, NotRequired, Optional, Union

import pydantic
from pydantic import model_serializer
from typing_extensions import TypedDict

from friendli.core.types import UNSET_SENTINEL, BaseModel
from friendli.core.utils import FieldMetadata, MultipartFormMetadata


class BodyUploadRawSamplesFileTypedDict(TypedDict):
    file_name: str
    content: bytes | IO[bytes] | io.IOBase
    content_type: NotRequired[str]


class BodyUploadRawSamplesFile(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]
    content: Annotated[
        bytes | IO[bytes] | io.IOBase,
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]
    content_type: Annotated[
        str | None, pydantic.Field(alias="Content-Type"), FieldMetadata(multipart=True)
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contentType"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        return m


class BodyUploadRawSamplesTypedDict(TypedDict):
    file: BodyUploadRawSamplesFileTypedDict
    "File to update samples."


class BodyUploadRawSamples(BaseModel):
    file: Annotated[
        BodyUploadRawSamplesFile,
        FieldMetadata(multipart=MultipartFormMetadata(file=True)),
    ]
    "File to update samples."
