"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .prompttokensdetails import PromptTokensDetails, PromptTokensDetailsTypedDict
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ChatUsageTypedDict(TypedDict):
    prompt_tokens: int
    "Number of tokens in the prompt."
    completion_tokens: int
    "Number of tokens in the generated chat completions."
    total_tokens: int
    "Total number of tokens used in the request (`prompt_tokens` + `completion_tokens`)."
    prompt_tokens_details: NotRequired[Nullable[PromptTokensDetailsTypedDict]]
    "Breakdown of tokens used in the prompt."


class ChatUsage(BaseModel):
    prompt_tokens: int
    "Number of tokens in the prompt."
    completion_tokens: int
    "Number of tokens in the generated chat completions."
    total_tokens: int
    "Total number of tokens used in the request (`prompt_tokens` + `completion_tokens`)."
    prompt_tokens_details: OptionalNullable[PromptTokensDetails] = UNSET
    "Breakdown of tokens used in the prompt."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["prompt_tokens_details"])
        nullable_fields = set(["prompt_tokens_details"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
