"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import List, Literal, NotRequired

from pydantic import model_serializer
from typing_extensions import TypedDict

from friendli.core.types import (
    UNSET,
    UNSET_SENTINEL,
    BaseModel,
    Nullable,
    OptionalNullable,
)

from .completionslogprobs import CompletionsLogprobs, CompletionsLogprobsTypedDict

CompletionsChoiceFinishReason = Literal["stop", "length"]
"Termination condition of the generation. `stop` means the API returned the full completions generated by the model without running into any limits. `length` means the generation exceeded `max_tokens` or the conversation exceeded the max context length."


class CompletionsChoiceTypedDict(TypedDict):
    index: int
    "The index of the choice in the list of generated choices."
    text: str
    "Generated text output."
    seed: int
    "Random seed used for the generation."
    finish_reason: CompletionsChoiceFinishReason
    "Termination condition of the generation. `stop` means the API returned the full completions generated by the model without running into any limits. `length` means the generation exceeded `max_tokens` or the conversation exceeded the max context length."
    tokens: list[int]
    "Generated output tokens."
    logprobs: NotRequired[Nullable[CompletionsLogprobsTypedDict]]


class CompletionsChoice(BaseModel):
    index: int
    "The index of the choice in the list of generated choices."
    text: str
    "Generated text output."
    seed: int
    "Random seed used for the generation."
    finish_reason: CompletionsChoiceFinishReason
    "Termination condition of the generation. `stop` means the API returned the full completions generated by the model without running into any limits. `length` means the generation exceeded `max_tokens` or the conversation exceeded the max context length."
    tokens: list[int]
    "Generated output tokens."
    logprobs: OptionalNullable[CompletionsLogprobs] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["logprobs"])
        nullable_fields = set(["logprobs"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
