"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .streamedaudiotranscriptiondata import (
    StreamedAudioTranscriptionData,
    StreamedAudioTranscriptionDataTypedDict,
)
from friendli.core.types import BaseModel
from typing_extensions import TypedDict


class ContainerAudioTranscriptionStreamSuccessTypedDict(TypedDict):
    data: StreamedAudioTranscriptionDataTypedDict


class ContainerAudioTranscriptionStreamSuccess(BaseModel):
    data: StreamedAudioTranscriptionData
