"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsesstreamevent import ResponsesStreamEvent, ResponsesStreamEventTypedDict
from friendli.core.types import BaseModel
from typing_extensions import TypedDict


class ContainerResponsesStreamSuccessTypedDict(TypedDict):
    data: ResponsesStreamEventTypedDict


class ContainerResponsesStreamSuccess(BaseModel):
    data: ResponsesStreamEvent
