"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from friendli.core.types import BaseModel

from .audiotranscriptionusage import (
    AudioTranscriptionUsage,
    AudioTranscriptionUsageTypedDict,
)


class ContainerAudioTranscriptionSuccessTypedDict(TypedDict):
    text: str
    "The transcribed text."
    usage: AudioTranscriptionUsageTypedDict


class ContainerAudioTranscriptionSuccess(BaseModel):
    text: str
    "The transcribed text."
    usage: AudioTranscriptionUsage
