"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, List, Literal, NotRequired

import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import (
    UNSET,
    UNSET_SENTINEL,
    BaseModel,
    Nullable,
    OptionalNullable,
)
from friendli.core.utils import validate_const

from .chatchoice import ChatChoice, ChatChoiceTypedDict
from .chatusage import ChatUsage, ChatUsageTypedDict


class ContainerChatCompleteSuccessTypedDict(TypedDict):
    id: str
    "A unique ID of the chat completion."
    choices: list[ChatChoiceTypedDict]
    usage: ChatUsageTypedDict
    created: int
    "The Unix timestamp (in seconds) for when the generation completed."
    object: Literal["chat.completion"]
    "The object type, which is always set to `chat.completion`."
    model: NotRequired[Nullable[str]]
    "The model to generate the completion. For dedicated endpoints, it returns the endpoint ID."


class ContainerChatCompleteSuccess(BaseModel):
    id: str
    "A unique ID of the chat completion."
    choices: list[ChatChoice]
    usage: ChatUsage
    created: int
    "The Unix timestamp (in seconds) for when the generation completed."
    OBJECT: Annotated[
        Annotated[
            Literal["chat.completion"],
            AfterValidator(validate_const("chat.completion")),
        ],
        pydantic.Field(alias="object"),
    ] = "chat.completion"
    "The object type, which is always set to `chat.completion`."
    model: OptionalNullable[str] = UNSET
    "The model to generate the completion. For dedicated endpoints, it returns the endpoint ID."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["model"])
        nullable_fields = set(["model"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    ContainerChatCompleteSuccess.model_rebuild()
except NameError:
    pass
