"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from friendli.core.types import BaseModel

from .messagesstreamevent import MessagesStreamEvent, MessagesStreamEventTypedDict


class ContainerMessagesStreamSuccessTypedDict(TypedDict):
    data: MessagesStreamEventTypedDict


class ContainerMessagesStreamSuccess(BaseModel):
    data: MessagesStreamEvent
