"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import List, NotRequired, Union

from pydantic import model_serializer
from typing_extensions import TypeAliasType, TypedDict

from friendli.core.types import (
    UNSET,
    UNSET_SENTINEL,
    BaseModel,
    Nullable,
    OptionalNullable,
)

ContainerTextClassificationBodyInputTypedDict = TypeAliasType(
    "ContainerTextClassificationBodyInputTypedDict", str | list[str]
)
"Input text to classify, encoded as a string or array of strings. To classify multiple inputs in a single request, pass an array of strings.\n\nEither `input` or `tokens` field is required.\n"
ContainerTextClassificationBodyInput = TypeAliasType(
    "ContainerTextClassificationBodyInput", str | list[str]
)
"Input text to classify, encoded as a string or array of strings. To classify multiple inputs in a single request, pass an array of strings.\n\nEither `input` or `tokens` field is required.\n"


class ContainerTextClassificationBodyTypedDict(TypedDict):
    model: NotRequired[Nullable[str]]
    "Routes the request to a specific adapter."
    input: NotRequired[Nullable[ContainerTextClassificationBodyInputTypedDict]]
    "Input text to classify, encoded as a string or array of strings. To classify multiple inputs in a single request, pass an array of strings.\n\n    Either `input` or `tokens` field is required.\n    "
    tokens: NotRequired[Nullable[list[int]]]
    "The tokenized prompt (i.e., input tokens).\n\n    Either `input` or `tokens` field is required.\n    "


class ContainerTextClassificationBody(BaseModel):
    model: OptionalNullable[str] = UNSET
    "Routes the request to a specific adapter."
    input: OptionalNullable[ContainerTextClassificationBodyInput] = UNSET
    "Input text to classify, encoded as a string or array of strings. To classify multiple inputs in a single request, pass an array of strings.\n\n    Either `input` or `tokens` field is required.\n    "
    tokens: OptionalNullable[list[int]] = UNSET
    "The tokenized prompt (i.e., input tokens).\n\n    Either `input` or `tokens` field is required.\n    "

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["model", "input", "tokens"])
        nullable_fields = set(["model", "input", "tokens"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
