"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsesinputitem import ResponsesInputItem, ResponsesInputItemTypedDict
from .responsesreasoningconfig import (
    ResponsesReasoningConfig,
    ResponsesReasoningConfigTypedDict,
)
from .responsestextconfig import ResponsesTextConfig, ResponsesTextConfigTypedDict
from .responsestool import ResponsesTool, ResponsesToolTypedDict
from .responsestoolchoicecustom import (
    ResponsesToolChoiceCustom,
    ResponsesToolChoiceCustomTypedDict,
)
from .responsestoolchoicefunction import (
    ResponsesToolChoiceFunction,
    ResponsesToolChoiceFunctionTypedDict,
)
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict

ContainerResponsesStreamBodyInputTypedDict = TypeAliasType(
    "ContainerResponsesStreamBodyInputTypedDict",
    Union[str, List[ResponsesInputItemTypedDict]],
)
"Text or image inputs to the model, used to generate a response."
ContainerResponsesStreamBodyInput = TypeAliasType(
    "ContainerResponsesStreamBodyInput", Union[str, List[ResponsesInputItem]]
)
"Text or image inputs to the model, used to generate a response."
ContainerResponsesStreamBodyToolChoiceEnum = Literal["none", "auto", "required"]
ContainerResponsesStreamBodyToolChoiceUnionTypedDict = TypeAliasType(
    "ContainerResponsesStreamBodyToolChoiceUnionTypedDict",
    Union[
        ResponsesToolChoiceFunctionTypedDict,
        ResponsesToolChoiceCustomTypedDict,
        ContainerResponsesStreamBodyToolChoiceEnum,
    ],
)
"Controls which (if any) tool is called by the model. `none` means the model will not call any tool and instead generates a message. `auto` means the model can pick between generating a message or calling one or more tools. `required` means the model must call one or more tools. An object can be used to force the model to call a specific function or custom tool."
ContainerResponsesStreamBodyToolChoiceUnion = TypeAliasType(
    "ContainerResponsesStreamBodyToolChoiceUnion",
    Union[
        ResponsesToolChoiceFunction,
        ResponsesToolChoiceCustom,
        ContainerResponsesStreamBodyToolChoiceEnum,
    ],
)
"Controls which (if any) tool is called by the model. `none` means the model will not call any tool and instead generates a message. `auto` means the model can pick between generating a message or calling one or more tools. `required` means the model must call one or more tools. An object can be used to force the model to call a specific function or custom tool."


class ContainerResponsesStreamBodyTypedDict(TypedDict):
    input: ContainerResponsesStreamBodyInputTypedDict
    "Text or image inputs to the model, used to generate a response."
    instructions: NotRequired[Nullable[str]]
    "A system (or developer) message inserted into the model's context."
    max_output_tokens: NotRequired[Nullable[int]]
    "An upper bound for the number of tokens that can be generated for a response, including visible output tokens and reasoning tokens."
    temperature: NotRequired[Nullable[float]]
    "What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or `top_p` but not both."
    top_p: NotRequired[Nullable[float]]
    "An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with `top_p` probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or `temperature` but not both."
    parallel_tool_calls: NotRequired[Nullable[bool]]
    "Whether to allow the model to run tool calls in parallel."
    tools: NotRequired[Nullable[List[ResponsesToolTypedDict]]]
    "An array of tools the model may call while generating a response. You can specify which tool to use by setting the `tool_choice` parameter."
    tool_choice: NotRequired[
        Nullable[ContainerResponsesStreamBodyToolChoiceUnionTypedDict]
    ]
    "How the model should select which tool (or tools) to use when generating a response. See the `tools` parameter to see how to specify which tools the model can call."
    text: NotRequired[Nullable[ResponsesTextConfigTypedDict]]
    "Configuration options for a text response from the model. Can be plain text or structured JSON data."
    reasoning: NotRequired[Nullable[ResponsesReasoningConfigTypedDict]]
    "Configuration options for reasoning models."
    stream: NotRequired[bool]
    "Whether to stream the generation result. When set to `true`, the response is sent as [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format) once generated."
    model: NotRequired[Nullable[str]]
    "Routes the request to a specific adapter."


class ContainerResponsesStreamBody(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)
    input: ContainerResponsesStreamBodyInput
    "Text or image inputs to the model, used to generate a response."
    instructions: OptionalNullable[str] = UNSET
    "A system (or developer) message inserted into the model's context."
    max_output_tokens: OptionalNullable[int] = UNSET
    "An upper bound for the number of tokens that can be generated for a response, including visible output tokens and reasoning tokens."
    temperature: OptionalNullable[float] = UNSET
    "What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or `top_p` but not both."
    top_p: OptionalNullable[float] = UNSET
    "An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with `top_p` probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or `temperature` but not both."
    parallel_tool_calls: OptionalNullable[bool] = UNSET
    "Whether to allow the model to run tool calls in parallel."
    tools: OptionalNullable[List[ResponsesTool]] = UNSET
    "An array of tools the model may call while generating a response. You can specify which tool to use by setting the `tool_choice` parameter."
    tool_choice: OptionalNullable[ContainerResponsesStreamBodyToolChoiceUnion] = UNSET
    "How the model should select which tool (or tools) to use when generating a response. See the `tools` parameter to see how to specify which tools the model can call."
    text: OptionalNullable[ResponsesTextConfig] = UNSET
    "Configuration options for a text response from the model. Can be plain text or structured JSON data."
    reasoning: OptionalNullable[ResponsesReasoningConfig] = UNSET
    "Configuration options for reasoning models."
    stream: Optional[bool] = True
    "Whether to stream the generation result. When set to `true`, the response is sent as [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format) once generated."
    model: OptionalNullable[str] = UNSET
    "Routes the request to a specific adapter."

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "instructions",
                "max_output_tokens",
                "temperature",
                "top_p",
                "parallel_tool_calls",
                "tools",
                "tool_choice",
                "text",
                "reasoning",
                "stream",
                "model",
            ]
        )
        nullable_fields = set(
            [
                "instructions",
                "max_output_tokens",
                "temperature",
                "top_p",
                "parallel_tool_calls",
                "tools",
                "tool_choice",
                "text",
                "reasoning",
                "model",
            ]
        )
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v
        return m
