"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import NotRequired

from pydantic import model_serializer
from typing_extensions import TypedDict

from friendli.core.types import (
    UNSET,
    UNSET_SENTINEL,
    BaseModel,
    Nullable,
    OptionalNullable,
)


class CostResultTypedDict(TypedDict):
    """Cost result for a single line item."""

    total: str
    "The total cost in USD."
    quantity: NotRequired[Nullable[str]]
    "When `group_by=line_item`, this field provides the quantity of the line item. For token-based line items, the unit is Million tokens (Mtok). For GPU time, the unit is hours."
    unit_price: NotRequired[Nullable[str]]
    "When `group_by=line_item`, this field provides the unit price of the line item in USD cents. For token-based line items, the unit is cents per Million tokens (cents/Mtok). For GPU time, the unit is cents per GPU-hour (cents/GPU-hour)."
    line_item: NotRequired[Nullable[str]]
    "When `group_by=line_item`, this field provides the line item name of the grouped costs result."


class CostResult(BaseModel):
    """Cost result for a single line item."""

    total: str
    "The total cost in USD."
    quantity: OptionalNullable[str] = UNSET
    "When `group_by=line_item`, this field provides the quantity of the line item. For token-based line items, the unit is Million tokens (Mtok). For GPU time, the unit is hours."
    unit_price: OptionalNullable[str] = UNSET
    "When `group_by=line_item`, this field provides the unit price of the line item in USD cents. For token-based line items, the unit is cents per Million tokens (cents/Mtok). For GPU time, the unit is cents per GPU-hour (cents/GPU-hour)."
    line_item: OptionalNullable[str] = UNSET
    "When `group_by=line_item`, this field provides the line item name of the grouped costs result."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["quantity", "unit_price", "line_item"])
        nullable_fields = set(["quantity", "unit_price", "line_item"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
