"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CostResultTypedDict(TypedDict):
    total: str
    "The total cost in USD."
    quantity: NotRequired[str]
    "When `group_by=line_item`, this field provides the quantity of the line item. For token-based line items, the unit is Million tokens (Mtok). For GPU time, the unit is hours."
    unit_price: NotRequired[str]
    "When `group_by=line_item`, this field provides the unit price of the line item in USD cents. For token-based line items, the unit is cents per Million tokens (cents/Mtok). For GPU time, the unit is cents per GPU-hour (cents/GPU-hour)."
    line_item: NotRequired[str]
    "When `group_by=line_item`, this field provides the line item name of the grouped costs result."


class CostResult(BaseModel):
    total: str
    "The total cost in USD."
    quantity: Optional[str] = None
    "When `group_by=line_item`, this field provides the quantity of the line item. For token-based line items, the unit is Million tokens (Mtok). For GPU time, the unit is hours."
    unit_price: Optional[str] = None
    "When `group_by=line_item`, this field provides the unit price of the line item in USD cents. For token-based line items, the unit is cents per Million tokens (cents/Mtok). For GPU time, the unit is cents per GPU-hour (cents/GPU-hour)."
    line_item: Optional[str] = None
    "When `group_by=line_item`, this field provides the line item name of the grouped costs result."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["quantity", "unit_price", "line_item"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        return m
