"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .costbucket import CostBucket, CostBucketTypedDict
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class CostResponseTypedDict(TypedDict):
    has_more: bool
    data: List[CostBucketTypedDict]
    next_page: NotRequired[Nullable[str]]


class CostResponse(BaseModel):
    has_more: bool
    data: List[CostBucket]
    next_page: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["next_page"])
        nullable_fields = set(["next_page"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
