"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from friendli.core.types import BaseModel

from .responsesstreamevent import ResponsesStreamEvent, ResponsesStreamEventTypedDict


class DedicatedResponsesStreamSuccessTypedDict(TypedDict):
    data: ResponsesStreamEventTypedDict


class DedicatedResponsesStreamSuccess(BaseModel):
    data: ResponsesStreamEvent
