"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagesstreamevent import MessagesStreamEvent, MessagesStreamEventTypedDict
from friendli.core.types import BaseModel
from typing_extensions import TypedDict


class DedicatedMessagesStreamSuccessTypedDict(TypedDict):
    data: MessagesStreamEventTypedDict


class DedicatedMessagesStreamSuccess(BaseModel):
    data: MessagesStreamEvent
