"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import FieldMetadata, HeaderMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class DedicatedTerminateEndpointRequestTypedDict(TypedDict):
    endpoint_id: str
    "The ID of the endpoint"
    x_friendli_team: NotRequired[Nullable[str]]
    "ID of team to run requests as (optional parameter)."


class DedicatedTerminateEndpointRequest(BaseModel):
    endpoint_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    "The ID of the endpoint"
    x_friendli_team: Annotated[
        OptionalNullable[str],
        pydantic.Field(alias="X-Friendli-Team"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = UNSET
    "ID of team to run requests as (optional parameter)."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["X-Friendli-Team"])
        nullable_fields = set(["X-Friendli-Team"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
