"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import List

from typing_extensions import TypedDict

from friendli.core.types import BaseModel


class DedicatedTokenizationSuccessTypedDict(TypedDict):
    tokens: list[int]
    "A list of token IDs."


class DedicatedTokenizationSuccess(BaseModel):
    tokens: list[int]
    "A list of token IDs."
