"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagesresponsecontentblock import (
    MessagesResponseContentBlock,
    MessagesResponseContentBlockTypedDict,
)
from .messagesusage import MessagesUsage, MessagesUsageTypedDict
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import validate_const
import pydantic
from pydantic import ConfigDict, model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict

DedicatedMessagesSuccessStopReason = Literal[
    "end_turn", "max_tokens", "tool_use", "stop_sequence"
]


class DedicatedMessagesSuccessTypedDict(TypedDict):
    id: str
    "Unique identifier for this message response."
    content: List[MessagesResponseContentBlockTypedDict]
    "Assistant output blocks in generation order."
    usage: MessagesUsageTypedDict
    type: Literal["message"]
    "Response object type (`message`)."
    role: Literal["assistant"]
    "Role of the output message author (`assistant`)."
    stop_reason: NotRequired[Nullable[DedicatedMessagesSuccessStopReason]]
    "Why generation stopped (`end_turn`, `max_tokens`, `tool_use`, `stop_sequence`)."
    stop_sequence: NotRequired[Nullable[str]]
    "Matched stop string when `stop_reason` is `stop_sequence`; otherwise null."
    model: NotRequired[Nullable[str]]
    "Model used to generate the response."


class DedicatedMessagesSuccess(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)
    id: str
    "Unique identifier for this message response."
    content: List[MessagesResponseContentBlock]
    "Assistant output blocks in generation order."
    usage: MessagesUsage
    TYPE: Annotated[
        Annotated[Literal["message"], AfterValidator(validate_const("message"))],
        pydantic.Field(alias="type"),
    ] = "message"
    "Response object type (`message`)."
    ROLE: Annotated[
        Annotated[Literal["assistant"], AfterValidator(validate_const("assistant"))],
        pydantic.Field(alias="role"),
    ] = "assistant"
    "Role of the output message author (`assistant`)."
    stop_reason: OptionalNullable[DedicatedMessagesSuccessStopReason] = UNSET
    "Why generation stopped (`end_turn`, `max_tokens`, `tool_use`, `stop_sequence`)."
    stop_sequence: OptionalNullable[str] = UNSET
    "Matched stop string when `stop_reason` is `stop_sequence`; otherwise null."
    model: OptionalNullable[str] = UNSET
    "Model used to generate the response."

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["stop_reason", "stop_sequence", "model"])
        nullable_fields = set(["stop_reason", "stop_sequence", "model"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v
        return m


try:
    DedicatedMessagesSuccess.model_rebuild()
except NameError:
    pass
