"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import List, NotRequired, Optional

from pydantic import model_serializer
from typing_extensions import TypedDict

from friendli.core.types import UNSET_SENTINEL, BaseModel

from .dedicateddatasetmodalitytype import DedicatedDatasetModalityType


class DedicatedDatasetModalityTypedDict(TypedDict):
    """Dataset modality."""

    input_modals: NotRequired[list[DedicatedDatasetModalityType]]
    output_modals: NotRequired[list[DedicatedDatasetModalityType]]


class DedicatedDatasetModality(BaseModel):
    """Dataset modality."""

    input_modals: list[DedicatedDatasetModalityType] | None = None
    output_modals: list[DedicatedDatasetModalityType] | None = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["input_modals", "output_modals"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        return m
