"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagesinputmessage import MessagesInputMessage, MessagesInputMessageTypedDict
from .messagesoutputconfig import MessagesOutputConfig, MessagesOutputConfigTypedDict
from .messagessystemtextblock import (
    MessagesSystemTextBlock,
    MessagesSystemTextBlockTypedDict,
)
from .messagesthinkingconfig import (
    MessagesThinkingConfig,
    MessagesThinkingConfigTypedDict,
)
from .messagestoolchoice import MessagesToolChoice, MessagesToolChoiceTypedDict
from .messagestooldefinition import (
    MessagesToolDefinition,
    MessagesToolDefinitionTypedDict,
)
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict

DedicatedMessagesStreamBodySystemTypedDict = TypeAliasType(
    "DedicatedMessagesStreamBodySystemTypedDict",
    Union[str, List[MessagesSystemTextBlockTypedDict]],
)
"Payload format for the top-level `system` instruction."
DedicatedMessagesStreamBodySystem = TypeAliasType(
    "DedicatedMessagesStreamBodySystem", Union[str, List[MessagesSystemTextBlock]]
)
"Payload format for the top-level `system` instruction."
DedicatedMessagesStreamBodyServiceTierTypedDict = TypeAliasType(
    "DedicatedMessagesStreamBodyServiceTierTypedDict", Union[str, Dict[str, Any]]
)
"Compatibility field accepted for request portability. Parsed but not used for generation."
DedicatedMessagesStreamBodyServiceTier = TypeAliasType(
    "DedicatedMessagesStreamBodyServiceTier", Union[str, Dict[str, Any]]
)
"Compatibility field accepted for request portability. Parsed but not used for generation."


class DedicatedMessagesStreamBodyTypedDict(TypedDict):
    messages: List[MessagesInputMessageTypedDict]
    "A list of conversation messages ordered from oldest to newest. Must contain at least one item."
    model: str
    'ID of target endpoint. If you want to send request to specific adapter, use the format \\"YOUR_ENDPOINT_ID:YOUR_ADAPTER_ROUTE\\". Otherwise, you can just use \\"YOUR_ENDPOINT_ID\\" alone.'
    max_tokens: NotRequired[Nullable[int]]
    "Maximum number of tokens to generate for the assistant response. Must be greater than 0 when provided."
    system: NotRequired[Nullable[DedicatedMessagesStreamBodySystemTypedDict]]
    "Optional top-level system instruction applied before conversation turns. Supports a plain string or an array of text blocks."
    stream: NotRequired[bool]
    "Whether to stream the response. When set to `true`, events are sent as [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format) once generated."
    temperature: NotRequired[Nullable[float]]
    "Sampling temperature. Lower values make outputs more deterministic; higher values increase diversity."
    top_p: NotRequired[Nullable[float]]
    "Nucleus sampling parameter. The model samples from the smallest token set whose cumulative probability reaches `top_p`."
    top_k: NotRequired[Nullable[int]]
    "Limits sampling to the `k` most likely tokens at each decoding step."
    stop_sequences: NotRequired[Nullable[List[str]]]
    "Stop strings that terminate generation when matched in output. The matched value is returned in `stop_sequence` when applicable."
    tools: NotRequired[Nullable[List[MessagesToolDefinitionTypedDict]]]
    "Tool definitions available to the model. Use this to allow tool calls with structured arguments."
    tool_choice: NotRequired[Nullable[MessagesToolChoiceTypedDict]]
    "Controls tool-calling behavior (`auto`, `any`, `tool`, `none`) and optional parallel-call behavior."
    thinking: NotRequired[Nullable[MessagesThinkingConfigTypedDict]]
    "Controls reasoning behavior with mode (`enabled`, `disabled`, `adaptive`). `enabled` requires `budget_tokens`; `disabled` and `adaptive` must not include it."
    output_config: NotRequired[Nullable[MessagesOutputConfigTypedDict]]
    "Output generation options including effort level and structured output format settings."
    cache_control: NotRequired[Nullable[Dict[str, Any]]]
    "Compatibility field accepted for request portability. Parsed but not used for generation."
    container: NotRequired[Nullable[Dict[str, Any]]]
    "Compatibility field accepted for request portability. Parsed but not used for generation."
    context_manager: NotRequired[Nullable[Dict[str, Any]]]
    "Compatibility field accepted for request portability. Parsed but not used for generation."
    inference_geo: NotRequired[Nullable[Dict[str, Any]]]
    "Compatibility field accepted for request portability. Parsed but not used for generation."
    metadata: NotRequired[Nullable[Dict[str, Any]]]
    "Compatibility field accepted for request portability. Parsed but not used for generation."
    service_tier: NotRequired[Nullable[DedicatedMessagesStreamBodyServiceTierTypedDict]]
    "Compatibility field accepted for request portability. Parsed but not used for generation."


class DedicatedMessagesStreamBody(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)
    messages: List[MessagesInputMessage]
    "A list of conversation messages ordered from oldest to newest. Must contain at least one item."
    model: str
    'ID of target endpoint. If you want to send request to specific adapter, use the format \\"YOUR_ENDPOINT_ID:YOUR_ADAPTER_ROUTE\\". Otherwise, you can just use \\"YOUR_ENDPOINT_ID\\" alone.'
    max_tokens: OptionalNullable[int] = UNSET
    "Maximum number of tokens to generate for the assistant response. Must be greater than 0 when provided."
    system: OptionalNullable[DedicatedMessagesStreamBodySystem] = UNSET
    "Optional top-level system instruction applied before conversation turns. Supports a plain string or an array of text blocks."
    stream: Optional[bool] = True
    "Whether to stream the response. When set to `true`, events are sent as [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format) once generated."
    temperature: OptionalNullable[float] = UNSET
    "Sampling temperature. Lower values make outputs more deterministic; higher values increase diversity."
    top_p: OptionalNullable[float] = UNSET
    "Nucleus sampling parameter. The model samples from the smallest token set whose cumulative probability reaches `top_p`."
    top_k: OptionalNullable[int] = UNSET
    "Limits sampling to the `k` most likely tokens at each decoding step."
    stop_sequences: OptionalNullable[List[str]] = UNSET
    "Stop strings that terminate generation when matched in output. The matched value is returned in `stop_sequence` when applicable."
    tools: OptionalNullable[List[MessagesToolDefinition]] = UNSET
    "Tool definitions available to the model. Use this to allow tool calls with structured arguments."
    tool_choice: OptionalNullable[MessagesToolChoice] = UNSET
    "Controls tool-calling behavior (`auto`, `any`, `tool`, `none`) and optional parallel-call behavior."
    thinking: OptionalNullable[MessagesThinkingConfig] = UNSET
    "Controls reasoning behavior with mode (`enabled`, `disabled`, `adaptive`). `enabled` requires `budget_tokens`; `disabled` and `adaptive` must not include it."
    output_config: OptionalNullable[MessagesOutputConfig] = UNSET
    "Output generation options including effort level and structured output format settings."
    cache_control: OptionalNullable[Dict[str, Any]] = UNSET
    "Compatibility field accepted for request portability. Parsed but not used for generation."
    container: OptionalNullable[Dict[str, Any]] = UNSET
    "Compatibility field accepted for request portability. Parsed but not used for generation."
    context_manager: OptionalNullable[Dict[str, Any]] = UNSET
    "Compatibility field accepted for request portability. Parsed but not used for generation."
    inference_geo: OptionalNullable[Dict[str, Any]] = UNSET
    "Compatibility field accepted for request portability. Parsed but not used for generation."
    metadata: OptionalNullable[Dict[str, Any]] = UNSET
    "Compatibility field accepted for request portability. Parsed but not used for generation."
    service_tier: OptionalNullable[DedicatedMessagesStreamBodyServiceTier] = UNSET
    "Compatibility field accepted for request portability. Parsed but not used for generation."

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "max_tokens",
                "system",
                "stream",
                "temperature",
                "top_p",
                "top_k",
                "stop_sequences",
                "tools",
                "tool_choice",
                "thinking",
                "output_config",
                "cache_control",
                "container",
                "context_manager",
                "inference_geo",
                "metadata",
                "service_tier",
            ]
        )
        nullable_fields = set(
            [
                "max_tokens",
                "system",
                "temperature",
                "top_p",
                "top_k",
                "stop_sequences",
                "tools",
                "tool_choice",
                "thinking",
                "output_config",
                "cache_control",
                "container",
                "context_manager",
                "inference_geo",
                "metadata",
                "service_tier",
            ]
        )
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v
        return m
