"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .accountfilestatus import AccountFileStatus
from datetime import datetime
from friendli.core.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, TypedDict


class FileInfoTypedDict(TypedDict):
    """File information."""

    id: str
    "ID of the file."
    name: str
    "Name of the file."
    size: int
    "Size of the file in bytes."
    digest: str
    "SHA256 hash of the file."
    project_id: str
    "ID of the project the file belongs to."
    creator_id: str
    "ID of the creator of the file."
    created_at: datetime
    "Unix timestamp (in seconds) of when the file was created."
    expires_at: Nullable[datetime]
    "Unix timestamp (in seconds) of when the file will expire."
    status: AccountFileStatus
    "AccountFile status."


class FileInfo(BaseModel):
    """File information."""

    id: str
    "ID of the file."
    name: str
    "Name of the file."
    size: int
    "Size of the file in bytes."
    digest: str
    "SHA256 hash of the file."
    project_id: Annotated[str, pydantic.Field(alias="projectId")]
    "ID of the project the file belongs to."
    creator_id: Annotated[str, pydantic.Field(alias="creatorId")]
    "ID of the creator of the file."
    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]
    "Unix timestamp (in seconds) of when the file was created."
    expires_at: Annotated[Nullable[datetime], pydantic.Field(alias="expiresAt")]
    "Unix timestamp (in seconds) of when the file will expire."
    status: AccountFileStatus
    "AccountFile status."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            if val != UNSET_SENTINEL:
                m[k] = val
        return m


try:
    FileInfo.model_rebuild()
except NameError:
    pass
