"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict

FriendliBuiltInToolType = Literal[
    "math:calculator",
    "math:statistics",
    "math:calendar",
    "web:search",
    "web:url",
    "code:python-interpreter",
]
"The type of the built-in tool provided by Friendli."


class FriendliBuiltInToolTypedDict(TypedDict):
    type: FriendliBuiltInToolType
    "The type of the built-in tool provided by Friendli."


class FriendliBuiltInTool(BaseModel):
    type: FriendliBuiltInToolType
    "The type of the built-in tool provided by Friendli."
