"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .costbucketwidth import CostBucketWidth
from .costgroupby import CostGroupBy
from datetime import datetime
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import FieldMetadata, HeaderMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class GetCostRequestTypedDict(TypedDict):
    start_time: datetime
    "RFC 3339 timestamp in UTC. The time portion must be zeroed out (e.g., 2026-01-01T00:00:00Z). Must be no earlier than one year ago."
    end_time: datetime
    "RFC 3339 timestamp in UTC. The time portion must be zeroed out (e.g., 2026-01-02T00:00:00Z)."
    bucket_width: NotRequired[Nullable[CostBucketWidth]]
    "Width of each time bucket in response. Currently only `1d` is supported, default to `1d`."
    limit: NotRequired[Nullable[int]]
    "A limit on the number of buckets to be returned. Limit can range between 1 and 35, and the default is 7."
    page: NotRequired[Nullable[str]]
    "A cursor for use in pagination. Corresponding to the `next_page` field from the previous response."
    group_by: NotRequired[Nullable[CostGroupBy]]
    "Group the costs by the specified fields. Currently only `line_item` is supported."
    x_friendli_team: NotRequired[Nullable[str]]
    "ID of team to run requests as (optional parameter)."


class GetCostRequest(BaseModel):
    start_time: Annotated[
        datetime, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    "RFC 3339 timestamp in UTC. The time portion must be zeroed out (e.g., 2026-01-01T00:00:00Z). Must be no earlier than one year ago."
    end_time: Annotated[
        datetime, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    "RFC 3339 timestamp in UTC. The time portion must be zeroed out (e.g., 2026-01-02T00:00:00Z)."
    bucket_width: Annotated[
        OptionalNullable[CostBucketWidth],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "Width of each time bucket in response. Currently only `1d` is supported, default to `1d`."
    limit: Annotated[
        OptionalNullable[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "A limit on the number of buckets to be returned. Limit can range between 1 and 35, and the default is 7."
    page: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "A cursor for use in pagination. Corresponding to the `next_page` field from the previous response."
    group_by: Annotated[
        OptionalNullable[CostGroupBy],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "Group the costs by the specified fields. Currently only `line_item` is supported."
    x_friendli_team: Annotated[
        OptionalNullable[str],
        pydantic.Field(alias="X-Friendli-Team"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = UNSET
    "ID of team to run requests as (optional parameter)."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["bucket_width", "limit", "page", "group_by", "X-Friendli-Team"]
        )
        nullable_fields = set(
            ["bucket_width", "limit", "page", "group_by", "X-Friendli-Team"]
        )
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
