"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, List, NotRequired

import pydantic
from pydantic import model_serializer
from typing_extensions import TypedDict

from friendli.core.types import (
    UNSET,
    UNSET_SENTINEL,
    BaseModel,
    Nullable,
    OptionalNullable,
)
from friendli.core.utils import FieldMetadata, HeaderMetadata, QueryParamMetadata

from .producttype import ProductType
from .usagebucketwidth import UsageBucketWidth
from .usagegroupby import UsageGroupBy


class GetUsageRequestTypedDict(TypedDict):
    start_time: datetime
    "RFC 3339 timestamp in UTC. Must fall on a 5-minute boundary (e.g., 2026-01-01T10:05:00Z). It must be no earlier than one year ago. When `bucket_width=1h`, it must align to an hour boundary (e.g., `10:00:00Z`); when `bucket_width=1d`, it must align to a day boundary (e.g., `00:00:00Z`)."
    end_time: datetime
    "RFC 3339 timestamp in UTC. Must fall on a 5-minute boundary (e.g., 2026-01-01T10:05:00Z), and its minute value must match `start_time`'s. It must obey the same hour/day alignment as `start_time` when `bucket_width=1h` or `1d`."
    bucket_width: NotRequired[Nullable[UsageBucketWidth]]
    "Width of each time bucket in response. Currently `1d`, `1h`, and `5m` are supported, default to `1d`."
    limit: NotRequired[Nullable[int]]
    "Specifies the number of buckets to return.\n    - `bucket_width=1d`: default limit = 7, max limit = 31\n    - `bucket_width=1h`: default limit = 24, max limit = 168\n    - `bucket_width=5m`: default limit = 12, max limit = 288\n    "
    page: NotRequired[Nullable[str]]
    "A cursor for use in pagination. Corresponding to the `next_page` field from the previous response."
    group_by: NotRequired[Nullable[list[UsageGroupBy]]]
    "Group the usage by the specified fields. Support fields include `model`, `product_type`, `user_id` and any combination of them."
    models: NotRequired[Nullable[list[str]]]
    "Return only usage for the listed Model APIs and Dedicated Endpoints. Values are model IDs, endpoint IDs, or a mix."
    user_ids: NotRequired[Nullable[list[str]]]
    "Return only usage for these users."
    product_types: NotRequired[Nullable[list[ProductType]]]
    "Return only usage for the specified product types. Supported fields include `model_apis`, `dedicated_endpoints` and any combination of them."
    gpu_types: NotRequired[Nullable[list[str]]]
    "Return only usage for the specified GPU types. When this filter is given, only 'gpu_usage' will be provided. Combining `gpu_types` with 'product_types=model_apis` is rejected with HTTP 400."
    x_friendli_team: NotRequired[Nullable[str]]
    "ID of team to run requests as (optional parameter)."


class GetUsageRequest(BaseModel):
    start_time: Annotated[
        datetime, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    "RFC 3339 timestamp in UTC. Must fall on a 5-minute boundary (e.g., 2026-01-01T10:05:00Z). It must be no earlier than one year ago. When `bucket_width=1h`, it must align to an hour boundary (e.g., `10:00:00Z`); when `bucket_width=1d`, it must align to a day boundary (e.g., `00:00:00Z`)."
    end_time: Annotated[
        datetime, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    "RFC 3339 timestamp in UTC. Must fall on a 5-minute boundary (e.g., 2026-01-01T10:05:00Z), and its minute value must match `start_time`'s. It must obey the same hour/day alignment as `start_time` when `bucket_width=1h` or `1d`."
    bucket_width: Annotated[
        OptionalNullable[UsageBucketWidth],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "Width of each time bucket in response. Currently `1d`, `1h`, and `5m` are supported, default to `1d`."
    limit: Annotated[
        OptionalNullable[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "Specifies the number of buckets to return.\n    - `bucket_width=1d`: default limit = 7, max limit = 31\n    - `bucket_width=1h`: default limit = 24, max limit = 168\n    - `bucket_width=5m`: default limit = 12, max limit = 288\n    "
    page: Annotated[
        OptionalNullable[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "A cursor for use in pagination. Corresponding to the `next_page` field from the previous response."
    group_by: Annotated[
        OptionalNullable[list[UsageGroupBy]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "Group the usage by the specified fields. Support fields include `model`, `product_type`, `user_id` and any combination of them."
    models: Annotated[
        OptionalNullable[list[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "Return only usage for the listed Model APIs and Dedicated Endpoints. Values are model IDs, endpoint IDs, or a mix."
    user_ids: Annotated[
        OptionalNullable[list[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "Return only usage for these users."
    product_types: Annotated[
        OptionalNullable[list[ProductType]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "Return only usage for the specified product types. Supported fields include `model_apis`, `dedicated_endpoints` and any combination of them."
    gpu_types: Annotated[
        OptionalNullable[list[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    "Return only usage for the specified GPU types. When this filter is given, only 'gpu_usage' will be provided. Combining `gpu_types` with 'product_types=model_apis` is rejected with HTTP 400."
    x_friendli_team: Annotated[
        OptionalNullable[str],
        pydantic.Field(alias="X-Friendli-Team"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = UNSET
    "ID of team to run requests as (optional parameter)."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "bucket_width",
                "limit",
                "page",
                "group_by",
                "models",
                "user_ids",
                "product_types",
                "gpu_types",
                "X-Friendli-Team",
            ]
        )
        nullable_fields = set(
            [
                "bucket_width",
                "limit",
                "page",
                "group_by",
                "models",
                "user_ids",
                "product_types",
                "gpu_types",
                "X-Friendli-Team",
            ]
        )
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
