"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from friendli.core.types import BaseModel


class ImageInputTypedDict(TypedDict):
    image: str
    "An input image, provided either as a URL or a base64-encoded string. Maximum supported image size is 50 MiB."


class ImageInput(BaseModel):
    image: str
    "An input image, provided either as a URL or a base64-encoded string. Maximum supported image size is 50 MiB."
