"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
import io
import pydantic
from pydantic import model_serializer
from typing import IO, Literal, Union
from typing_extensions import Annotated, NotRequired, TypedDict

ListSamplesDirection = Literal["asc", "desc"]


class ListSamplesRequestTypedDict(TypedDict):
    dataset_id: str
    "ID of the dataset."
    split_id: str
    "ID of the split."
    cursor: NotRequired[Nullable[Union[bytes, IO[bytes], io.IOBase]]]
    limit: NotRequired[Nullable[int]]
    direction: NotRequired[Nullable[ListSamplesDirection]]
    version_id: NotRequired[Nullable[str]]
    x_friendli_team: NotRequired[Nullable[str]]
    "ID of team to run requests as (optional parameter)."


class ListSamplesRequest(BaseModel):
    dataset_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    "ID of the dataset."
    split_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    "ID of the split."
    cursor: Annotated[
        OptionalNullable[Union[bytes, IO[bytes], io.IOBase]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    limit: Annotated[
        OptionalNullable[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    direction: Annotated[
        OptionalNullable[ListSamplesDirection],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    version_id: Annotated[
        OptionalNullable[str],
        pydantic.Field(alias="versionId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    x_friendli_team: Annotated[
        OptionalNullable[str],
        pydantic.Field(alias="X-Friendli-Team"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = UNSET
    "ID of team to run requests as (optional parameter)."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["cursor", "limit", "direction", "versionId", "X-Friendli-Team"]
        )
        nullable_fields = set(
            ["cursor", "limit", "direction", "versionId", "X-Friendli-Team"]
        )
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
