"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .datasetinfo import DatasetInfo, DatasetInfoTypedDict
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class ListDatasetsResponseTypedDict(TypedDict):
    """List datasets response."""

    data: List[DatasetInfoTypedDict]
    "List of items."
    next_cursor: NotRequired[Nullable[bytes]]
    "Next cursor to use for pagination. `None` indicates no more items to fetch."


class ListDatasetsResponse(BaseModel):
    """List datasets response."""

    data: List[DatasetInfo]
    "List of items."
    next_cursor: Annotated[
        OptionalNullable[bytes], pydantic.Field(alias="nextCursor")
    ] = UNSET
    "Next cursor to use for pagination. `None` indicates no more items to fetch."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["nextCursor"])
        nullable_fields = set(["nextCursor"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    ListDatasetsResponse.model_rebuild()
except NameError:
    pass
