"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Literal

import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import BaseModel
from friendli.core.utils import validate_const


class MessagesStreamStartTextBlockTypedDict(TypedDict):
    text: str
    "Text content when `type=text`."
    type: Literal["text"]
    "Content block type."


class MessagesStreamStartTextBlock(BaseModel):
    text: str
    "Text content when `type=text`."
    TYPE: Annotated[
        Annotated[Literal["text"], AfterValidator(validate_const("text"))],
        pydantic.Field(alias="type"),
    ] = "text"
    "Content block type."


try:
    MessagesStreamStartTextBlock.model_rebuild()
except NameError:
    pass
