"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from friendli.core.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class MessagesSystemTextBlockTypedDict(TypedDict):
    text: str
    "System instruction text content."
    type: Literal["text"]
    "System block type. Must be `text`."


class MessagesSystemTextBlock(BaseModel):
    text: str
    "System instruction text content."
    TYPE: Annotated[
        Annotated[Literal["text"], AfterValidator(validate_const("text"))],
        pydantic.Field(alias="type"),
    ] = "text"
    "System block type. Must be `text`."


try:
    MessagesSystemTextBlock.model_rebuild()
except NameError:
    pass
