"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Literal

import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import BaseModel
from friendli.core.utils import validate_const


class MessagesStreamTextDeltaTypedDict(TypedDict):
    text: str
    "Text fragment when `type=text_delta`."
    type: Literal["text_delta"]
    "Delta type."


class MessagesStreamTextDelta(BaseModel):
    text: str
    "Text fragment when `type=text_delta`."
    TYPE: Annotated[
        Annotated[Literal["text_delta"], AfterValidator(validate_const("text_delta"))],
        pydantic.Field(alias="type"),
    ] = "text_delta"
    "Delta type."


try:
    MessagesStreamTextDelta.model_rebuild()
except NameError:
    pass
