"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Any, Dict
from typing_extensions import NotRequired, TypedDict


class MessagesToolDefinitionTypedDict(TypedDict):
    name: str
    "Tool identifier used in model tool-call outputs. Keep this name stable and unique within the request."
    type: NotRequired[Nullable[str]]
    "Tool category. If missing, empty, or `custom`, it is converted to a function tool. Any non-empty value other than `custom` is treated as a server-side tool and skipped."
    description: NotRequired[Nullable[str]]
    "Natural-language description of what the tool does and when to call it."
    input_schema: NotRequired[Nullable[Dict[str, Any]]]
    "JSON Schema describing tool arguments. The model uses this schema to construct the tool input object."
    strict: NotRequired[Nullable[bool]]
    "If true, applies stricter schema adherence when generating tool arguments."


class MessagesToolDefinition(BaseModel):
    name: str
    "Tool identifier used in model tool-call outputs. Keep this name stable and unique within the request."
    type: OptionalNullable[str] = UNSET
    "Tool category. If missing, empty, or `custom`, it is converted to a function tool. Any non-empty value other than `custom` is treated as a server-side tool and skipped."
    description: OptionalNullable[str] = UNSET
    "Natural-language description of what the tool does and when to call it."
    input_schema: OptionalNullable[Dict[str, Any]] = UNSET
    "JSON Schema describing tool arguments. The model uses this schema to construct the tool input object."
    strict: OptionalNullable[bool] = UNSET
    "If true, applies stricter schema adherence when generating tool arguments."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "description", "input_schema", "strict"])
        nullable_fields = set(["type", "description", "input_schema", "strict"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
