"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Literal, NotRequired

from pydantic import model_serializer
from typing_extensions import TypedDict

from friendli.core.types import (
    UNSET,
    UNSET_SENTINEL,
    BaseModel,
    Nullable,
    OptionalNullable,
)

MessagesStreamMessageDeltaPayloadStopReason = Literal[
    "end_turn", "max_tokens", "tool_use", "stop_sequence"
]


class MessagesStreamMessageDeltaPayloadTypedDict(TypedDict):
    stop_reason: NotRequired[Nullable[MessagesStreamMessageDeltaPayloadStopReason]]
    "Why generation stopped."
    stop_sequence: NotRequired[Nullable[str]]
    "Matched stop sequence when `stop_reason=stop_sequence`."


class MessagesStreamMessageDeltaPayload(BaseModel):
    stop_reason: OptionalNullable[MessagesStreamMessageDeltaPayloadStopReason] = UNSET
    "Why generation stopped."
    stop_sequence: OptionalNullable[str] = UNSET
    "Matched stop sequence when `stop_reason=stop_sequence`."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["stop_reason", "stop_sequence"])
        nullable_fields = set(["stop_reason", "stop_sequence"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
