"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Literal

import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import BaseModel
from friendli.core.utils import validate_const

from .messagesimagesource import MessagesImageSource, MessagesImageSourceTypedDict


class MessagesImageBlockTypedDict(TypedDict):
    source: MessagesImageSourceTypedDict
    type: Literal["image"]
    "Content block type. Must be `image`."


class MessagesImageBlock(BaseModel):
    source: MessagesImageSource
    TYPE: Annotated[
        Annotated[Literal["image"], AfterValidator(validate_const("image"))],
        pydantic.Field(alias="type"),
    ] = "image"
    "Content block type. Must be `image`."


try:
    MessagesImageBlock.model_rebuild()
except NameError:
    pass
