"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from friendli.core.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class MessagesResponseThinkingBlockTypedDict(TypedDict):
    thinking: str
    "Reasoning content returned by the model."
    signature: str
    "Signature associated with the reasoning content."
    type: Literal["thinking"]
    "Content block type."


class MessagesResponseThinkingBlock(BaseModel):
    thinking: str
    "Reasoning content returned by the model."
    signature: str
    "Signature associated with the reasoning content."
    TYPE: Annotated[
        Annotated[Literal["thinking"], AfterValidator(validate_const("thinking"))],
        pydantic.Field(alias="type"),
    ] = "thinking"
    "Content block type."


try:
    MessagesResponseThinkingBlock.model_rebuild()
except NameError:
    pass
