"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagescontentblock import MessagesContentBlock, MessagesContentBlockTypedDict
from friendli.core.types import BaseModel
from typing import List, Literal, Union
from typing_extensions import TypeAliasType, TypedDict

Role = Literal["user", "assistant"]
"Author role for this message turn. Use `user` for user input and `assistant` for prior assistant turns."
MessagesInputMessageContentTypedDict = TypeAliasType(
    "MessagesInputMessageContentTypedDict",
    Union[str, List[MessagesContentBlockTypedDict]],
)
"Message payload. Supports plain string shorthand or a typed block array."
MessagesInputMessageContent = TypeAliasType(
    "MessagesInputMessageContent", Union[str, List[MessagesContentBlock]]
)
"Message payload. Supports plain string shorthand or a typed block array."


class MessagesInputMessageTypedDict(TypedDict):
    role: Role
    "Author role for this message turn. Use `user` for user input and `assistant` for prior assistant turns."
    content: MessagesInputMessageContentTypedDict
    "Message payload. Supports plain string shorthand or a typed block array."


class MessagesInputMessage(BaseModel):
    role: Role
    "Author role for this message turn. Use `user` for user input and `assistant` for prior assistant turns."
    content: MessagesInputMessageContent
    "Message payload. Supports plain string shorthand or a typed block array."
