"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagesstreaminputjsondelta import (
    MessagesStreamInputJSONDelta,
    MessagesStreamInputJSONDeltaTypedDict,
)
from .messagesstreamsignaturedelta import (
    MessagesStreamSignatureDelta,
    MessagesStreamSignatureDeltaTypedDict,
)
from .messagesstreamtextdelta import (
    MessagesStreamTextDelta,
    MessagesStreamTextDeltaTypedDict,
)
from .messagesstreamthinkingdelta import (
    MessagesStreamThinkingDelta,
    MessagesStreamThinkingDeltaTypedDict,
)
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType

MessagesStreamContentBlockDeltaPayloadTypedDict = TypeAliasType(
    "MessagesStreamContentBlockDeltaPayloadTypedDict",
    Union[
        MessagesStreamTextDeltaTypedDict,
        MessagesStreamThinkingDeltaTypedDict,
        MessagesStreamSignatureDeltaTypedDict,
        MessagesStreamInputJSONDeltaTypedDict,
    ],
)
MessagesStreamContentBlockDeltaPayload = Annotated[
    Union[
        MessagesStreamInputJSONDelta,
        MessagesStreamSignatureDelta,
        MessagesStreamTextDelta,
        MessagesStreamThinkingDelta,
    ],
    Field(discriminator="TYPE"),
]
