"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .messagesstreamstarttextblock import (
    MessagesStreamStartTextBlock,
    MessagesStreamStartTextBlockTypedDict,
)
from .messagesstreamstartthinkingblock import (
    MessagesStreamStartThinkingBlock,
    MessagesStreamStartThinkingBlockTypedDict,
)
from .messagesstreamstarttooluseblock import (
    MessagesStreamStartToolUseBlock,
    MessagesStreamStartToolUseBlockTypedDict,
)

MessagesStreamContentBlockStartPayloadTypedDict = TypeAliasType(
    "MessagesStreamContentBlockStartPayloadTypedDict",
    MessagesStreamStartTextBlockTypedDict
    | MessagesStreamStartThinkingBlockTypedDict
    | MessagesStreamStartToolUseBlockTypedDict,
)
MessagesStreamContentBlockStartPayload = Annotated[
    MessagesStreamStartTextBlock
    | MessagesStreamStartThinkingBlock
    | MessagesStreamStartToolUseBlock,
    Field(discriminator="TYPE"),
]
