"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .messagesbase64imagesource import (
    MessagesBase64ImageSource,
    MessagesBase64ImageSourceTypedDict,
)
from .messagesurlimagesource import (
    MessagesURLImageSource,
    MessagesURLImageSourceTypedDict,
)

MessagesImageSourceTypedDict = TypeAliasType(
    "MessagesImageSourceTypedDict",
    MessagesURLImageSourceTypedDict | MessagesBase64ImageSourceTypedDict,
)
MessagesImageSource = Annotated[
    MessagesBase64ImageSource | MessagesURLImageSource, Field(discriminator="TYPE")
]
