"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .assistantmessage import AssistantMessage, AssistantMessageTypedDict
from .systemmessage import SystemMessage, SystemMessageTypedDict
from .toolmessage import ToolMessage, ToolMessageTypedDict
from .usermessage import UserMessage, UserMessageTypedDict

MessageTypedDict = TypeAliasType(
    "MessageTypedDict",
    SystemMessageTypedDict
    | UserMessageTypedDict
    | ToolMessageTypedDict
    | AssistantMessageTypedDict,
)
Message = Annotated[
    AssistantMessage | SystemMessage | ToolMessage | UserMessage,
    Field(discriminator="ROLE"),
]
