"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .messagesstreamcontentblockdelta import (
    MessagesStreamContentBlockDelta,
    MessagesStreamContentBlockDeltaTypedDict,
)
from .messagesstreamcontentblockstart import (
    MessagesStreamContentBlockStart,
    MessagesStreamContentBlockStartTypedDict,
)
from .messagesstreamcontentblockstop import (
    MessagesStreamContentBlockStop,
    MessagesStreamContentBlockStopTypedDict,
)
from .messagesstreamerrorevent import (
    MessagesStreamErrorEvent,
    MessagesStreamErrorEventTypedDict,
)
from .messagesstreammessagedelta import (
    MessagesStreamMessageDelta,
    MessagesStreamMessageDeltaTypedDict,
)
from .messagesstreammessagestart import (
    MessagesStreamMessageStart,
    MessagesStreamMessageStartTypedDict,
)
from .messagesstreammessagestop import (
    MessagesStreamMessageStop,
    MessagesStreamMessageStopTypedDict,
)

MessagesStreamEventTypedDict = TypeAliasType(
    "MessagesStreamEventTypedDict",
    MessagesStreamMessageStopTypedDict
    | MessagesStreamMessageStartTypedDict
    | MessagesStreamContentBlockStopTypedDict
    | MessagesStreamContentBlockStartTypedDict
    | MessagesStreamContentBlockDeltaTypedDict
    | MessagesStreamMessageDeltaTypedDict
    | MessagesStreamErrorEventTypedDict,
)
MessagesStreamEvent = Annotated[
    MessagesStreamContentBlockDelta
    | MessagesStreamContentBlockStart
    | MessagesStreamContentBlockStop
    | MessagesStreamErrorEvent
    | MessagesStreamMessageDelta
    | MessagesStreamMessageStart
    | MessagesStreamMessageStop,
    Field(discriminator="TYPE"),
]
