"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Literal, NotRequired

import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import (
    UNSET,
    UNSET_SENTINEL,
    BaseModel,
    Nullable,
    OptionalNullable,
)
from friendli.core.utils import validate_const

from .messagesstreamerrordetail import (
    MessagesStreamErrorDetail,
    MessagesStreamErrorDetailTypedDict,
)


class MessagesStreamErrorEventTypedDict(TypedDict):
    error: MessagesStreamErrorDetailTypedDict
    type: Literal["error"]
    "The type of the event."
    request_id: NotRequired[Nullable[str]]
    "Request identifier for debugging and support."


class MessagesStreamErrorEvent(BaseModel):
    error: MessagesStreamErrorDetail
    TYPE: Annotated[
        Annotated[Literal["error"], AfterValidator(validate_const("error"))],
        pydantic.Field(alias="type"),
    ] = "error"
    "The type of the event."
    request_id: OptionalNullable[str] = UNSET
    "Request identifier for debugging and support."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["request_id"])
        nullable_fields = set(["request_id"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    MessagesStreamErrorEvent.model_rebuild()
except NameError:
    pass
