"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class MessagesStreamMessageDeltaUsageTypedDict(TypedDict):
    input_tokens: NotRequired[Nullable[int]]
    "Input token count delta when included."
    output_tokens: NotRequired[Nullable[int]]
    "Output token count delta when included."
    cache_read_input_tokens: NotRequired[Nullable[int]]
    "Cached input token count delta when included."


class MessagesStreamMessageDeltaUsage(BaseModel):
    input_tokens: OptionalNullable[int] = UNSET
    "Input token count delta when included."
    output_tokens: OptionalNullable[int] = UNSET
    "Output token count delta when included."
    cache_read_input_tokens: OptionalNullable[int] = UNSET
    "Cached input token count delta when included."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["input_tokens", "output_tokens", "cache_read_input_tokens"]
        )
        nullable_fields = set(
            ["input_tokens", "output_tokens", "cache_read_input_tokens"]
        )
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
