"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from friendli.core.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class MessagesURLImageSourceTypedDict(TypedDict):
    url: str
    "Publicly accessible image URL that the service can fetch."
    type: Literal["url"]
    "Image source type. Must be `url`."


class MessagesURLImageSource(BaseModel):
    url: str
    "Publicly accessible image URL that the service can fetch."
    TYPE: Annotated[
        Annotated[Literal["url"], AfterValidator(validate_const("url"))],
        pydantic.Field(alias="type"),
    ] = "url"
    "Image source type. Must be `url`."


try:
    MessagesURLImageSource.model_rebuild()
except NameError:
    pass
