"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class MessagesUsageTypedDict(TypedDict):
    input_tokens: int
    "Number of billed input tokens for this request."
    output_tokens: int
    "Number of billed output tokens generated by the model."
    cache_read_input_tokens: NotRequired[Nullable[int]]
    "Number of input tokens served from cache, when cache reads are applicable."


class MessagesUsage(BaseModel):
    input_tokens: int
    "Number of billed input tokens for this request."
    output_tokens: int
    "Number of billed output tokens generated by the model."
    cache_read_input_tokens: OptionalNullable[int] = UNSET
    "Number of input tokens served from cache, when cache reads are applicable."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cache_read_input_tokens"])
        nullable_fields = set(["cache_read_input_tokens"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
