"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class MessagesOutputFormatTypedDict(TypedDict):
    type: Nullable[Literal["json_schema"]]
    "Output format type. Set to `json_schema` to constrain output to a JSON schema."
    schema_: NotRequired[Nullable[Dict[str, Any]]]
    "JSON Schema object applied when `type` is `json_schema`."


class MessagesOutputFormat(BaseModel):
    TYPE: Annotated[
        Annotated[
            OptionalNullable[Literal["json_schema"]],
            AfterValidator(validate_const("json_schema")),
        ],
        pydantic.Field(alias="type"),
    ] = "json_schema"
    "Output format type. Set to `json_schema` to constrain output to a JSON schema."
    schema_: Annotated[
        OptionalNullable[Dict[str, Any]], pydantic.Field(alias="schema")
    ] = UNSET
    "JSON Schema object applied when `type` is `json_schema`."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "schema"])
        nullable_fields = set(["type", "schema"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    MessagesOutputFormat.model_rebuild()
except NameError:
    pass
