"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class MessagesThinkingBlockTypedDict(TypedDict):
    thinking: str
    "Reasoning content for this block."
    type: Literal["thinking"]
    "Content block type. Must be `thinking`."
    signature: NotRequired[Nullable[str]]
    "Optional signature associated with the reasoning content."


class MessagesThinkingBlock(BaseModel):
    thinking: str
    "Reasoning content for this block."
    TYPE: Annotated[
        Annotated[Literal["thinking"], AfterValidator(validate_const("thinking"))],
        pydantic.Field(alias="type"),
    ] = "thinking"
    "Content block type. Must be `thinking`."
    signature: OptionalNullable[str] = UNSET
    "Optional signature associated with the reasoning content."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["signature"])
        nullable_fields = set(["signature"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    MessagesThinkingBlock.model_rebuild()
except NameError:
    pass
