"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from friendli.core.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class MessagesStreamMessageStopTypedDict(TypedDict):
    type: Literal["message_stop"]
    "The type of the event."


class MessagesStreamMessageStop(BaseModel):
    TYPE: Annotated[
        Annotated[
            Literal["message_stop"], AfterValidator(validate_const("message_stop"))
        ],
        pydantic.Field(alias="type"),
    ] = "message_stop"
    "The type of the event."


try:
    MessagesStreamMessageStop.model_rebuild()
except NameError:
    pass
