"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from friendli.core.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class MessagesTextBlockTypedDict(TypedDict):
    text: str
    "Text content for this block."
    type: Literal["text"]
    "Content block type. Must be `text`."


class MessagesTextBlock(BaseModel):
    text: str
    "Text content for this block."
    TYPE: Annotated[
        Annotated[Literal["text"], AfterValidator(validate_const("text"))],
        pydantic.Field(alias="type"),
    ] = "text"
    "Content block type. Must be `text`."


try:
    MessagesTextBlock.model_rebuild()
except NameError:
    pass
