"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagesstreammessagedeltapayload import (
    MessagesStreamMessageDeltaPayload,
    MessagesStreamMessageDeltaPayloadTypedDict,
)
from .messagesstreammessagedeltausage import (
    MessagesStreamMessageDeltaUsage,
    MessagesStreamMessageDeltaUsageTypedDict,
)
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class MessagesStreamMessageDeltaTypedDict(TypedDict):
    delta: MessagesStreamMessageDeltaPayloadTypedDict
    type: Literal["message_delta"]
    "The type of the event."
    usage: NotRequired[Nullable[MessagesStreamMessageDeltaUsageTypedDict]]
    "Usage delta object that may be emitted near stream completion."


class MessagesStreamMessageDelta(BaseModel):
    delta: MessagesStreamMessageDeltaPayload
    TYPE: Annotated[
        Annotated[
            Literal["message_delta"], AfterValidator(validate_const("message_delta"))
        ],
        pydantic.Field(alias="type"),
    ] = "message_delta"
    "The type of the event."
    usage: OptionalNullable[MessagesStreamMessageDeltaUsage] = UNSET
    "Usage delta object that may be emitted near stream completion."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["usage"])
        nullable_fields = set(["usage"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    MessagesStreamMessageDelta.model_rebuild()
except NameError:
    pass
