"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from typing_extensions import TypedDict


class MessagesStreamErrorDetailTypedDict(TypedDict):
    type: str
    "Error category, such as `invalid_request_error`."
    message: str
    "Human-readable error message."


class MessagesStreamErrorDetail(BaseModel):
    type: str
    "Error category, such as `invalid_request_error`."
    message: str
    "Human-readable error message."
