"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagesstreamstarttextblock import (
    MessagesStreamStartTextBlock,
    MessagesStreamStartTextBlockTypedDict,
)
from .messagesstreamstartthinkingblock import (
    MessagesStreamStartThinkingBlock,
    MessagesStreamStartThinkingBlockTypedDict,
)
from .messagesstreamstarttooluseblock import (
    MessagesStreamStartToolUseBlock,
    MessagesStreamStartToolUseBlockTypedDict,
)
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType

MessagesStreamContentBlockStartPayloadTypedDict = TypeAliasType(
    "MessagesStreamContentBlockStartPayloadTypedDict",
    Union[
        MessagesStreamStartTextBlockTypedDict,
        MessagesStreamStartThinkingBlockTypedDict,
        MessagesStreamStartToolUseBlockTypedDict,
    ],
)
MessagesStreamContentBlockStartPayload = Annotated[
    Union[
        MessagesStreamStartTextBlock,
        MessagesStreamStartThinkingBlock,
        MessagesStreamStartToolUseBlock,
    ],
    Field(discriminator="TYPE"),
]
