"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Any, Dict, Literal

import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import BaseModel
from friendli.core.utils import validate_const


class MessagesResponseToolUseBlockTypedDict(TypedDict):
    id: str
    "Identifier of the tool call emitted by the model."
    name: str
    "Name of the invoked tool."
    input: dict[str, Any]
    "Parsed tool argument object generated by the model."
    type: Literal["tool_use"]
    "Content block type."


class MessagesResponseToolUseBlock(BaseModel):
    id: str
    "Identifier of the tool call emitted by the model."
    name: str
    "Name of the invoked tool."
    input: dict[str, Any]
    "Parsed tool argument object generated by the model."
    TYPE: Annotated[
        Annotated[Literal["tool_use"], AfterValidator(validate_const("tool_use"))],
        pydantic.Field(alias="type"),
    ] = "tool_use"
    "Content block type."


try:
    MessagesResponseToolUseBlock.model_rebuild()
except NameError:
    pass
