"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Literal

Modality = Literal["text", "audio", "image", "video", "pdf"]
"Supported input and output modalities."
