"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, List, Union

from pydantic import Field, model_serializer
from typing_extensions import TypeAliasType, TypedDict

from friendli.core.types import UNSET_SENTINEL, BaseModel, Nullable

from .defaultsamplingparams import DefaultSamplingParams, DefaultSamplingParamsTypedDict
from .functionality import Functionality, FunctionalityTypedDict
from .interleavedfield import InterleavedField
from .modality import Modality
from .mode import Mode
from .pricingmodel import PricingModel, PricingModelTypedDict
from .reasoningbudgettokens import ReasoningBudgetTokens, ReasoningBudgetTokensTypedDict
from .reasoningeffortoption import ReasoningEffortOption, ReasoningEffortOptionTypedDict
from .reasoningtoggle import ReasoningToggle, ReasoningToggleTypedDict

ReasoningOptionTypedDict = TypeAliasType(
    "ReasoningOptionTypedDict",
    ReasoningToggleTypedDict
    | ReasoningEffortOptionTypedDict
    | ReasoningBudgetTokensTypedDict,
)
ReasoningOption = Annotated[
    ReasoningBudgetTokens | ReasoningEffortOption | ReasoningToggle,
    Field(discriminator="TYPE"),
]
InterleavedTypedDict = TypeAliasType("InterleavedTypedDict", bool | InterleavedField)
"`false` means reasoning stays in `content` and cannot be separated. A string (`reasoning_content` or `reasoning_details`) means the model can parse reasoning into a top-level field of that name via `parse_reasoning`."
Interleaved = TypeAliasType("Interleaved", bool | InterleavedField)
"`false` means reasoning stays in `content` and cannot be separated. A string (`reasoning_content` or `reasoning_details`) means the model can parse reasoning into a top-level field of that name via `parse_reasoning`."


class ModelCatalogResponseItemTypedDict(TypedDict):
    """Model listing in `/v1/models` API."""

    id: str
    "Model identifier. Pass this as the `model` field in inference API requests."
    name: str
    "Display name of the model."
    created: int
    "Unix timestamp (seconds) of when Friendli started serving this model on Model APIs. Not the original model release date."
    context_length: int
    "Maximum tokens in a single request, shared between input and output."
    max_completion_tokens: int
    "Maximum number of tokens the model can generate in a single response (same as max output tokens)."
    pricing: PricingModelTypedDict
    "Pricing for a model, charged per individual token in USD."
    functionality: FunctionalityTypedDict
    "Whether the model supports specific features."
    description: str
    "Brief description of the model."
    deprecation_date: Nullable[str]
    "Scheduled deprecation date in ISO 8601 UTC (YYYY-MM-DDTHH:00:00Z). The model is inactive once this date has passed."
    reasoning: bool
    "Whether the model supports reasoning."
    reasoning_options: Nullable[list[ReasoningOptionTypedDict]]
    "Reasoning controls the model supports, such as toggling it on or off, selecting an effort level, or setting a token budget. A model may support more than one of these at the same time. Present only when reasoning is supported."
    input_modalities: list[Modality]
    "Input types the model accepts, such as text, image, or audio."
    output_modalities: list[Modality]
    "Output types the model can produce, such as text or image."
    interleaved: InterleavedTypedDict
    "`false` means reasoning stays in `content` and cannot be separated. A string (`reasoning_content` or `reasoning_details`) means the model can parse reasoning into a top-level field of that name via `parse_reasoning`."
    base_model: Nullable[str]
    "Canonical model identifier from models.dev (e.g. `zhipuai/glm-5.2`)."
    mode: Mode
    "Primary API endpoint type for this model.\n\n    ``chat`` routes requests to ``/v1/chat/completions``,\n    ``completion`` to ``/v1/completions``, and\n    ``embedding`` to ``/v1/embeddings``.\n    "
    default_params: Nullable[DefaultSamplingParamsTypedDict]
    "Default sampling parameters applied at inference time when the request does not specify them."


class ModelCatalogResponseItem(BaseModel):
    """Model listing in `/v1/models` API."""

    id: str
    "Model identifier. Pass this as the `model` field in inference API requests."
    name: str
    "Display name of the model."
    created: int
    "Unix timestamp (seconds) of when Friendli started serving this model on Model APIs. Not the original model release date."
    context_length: int
    "Maximum tokens in a single request, shared between input and output."
    max_completion_tokens: int
    "Maximum number of tokens the model can generate in a single response (same as max output tokens)."
    pricing: PricingModel
    "Pricing for a model, charged per individual token in USD."
    functionality: Functionality
    "Whether the model supports specific features."
    description: str
    "Brief description of the model."
    deprecation_date: Nullable[str]
    "Scheduled deprecation date in ISO 8601 UTC (YYYY-MM-DDTHH:00:00Z). The model is inactive once this date has passed."
    reasoning: bool
    "Whether the model supports reasoning."
    reasoning_options: Nullable[list[ReasoningOption]]
    "Reasoning controls the model supports, such as toggling it on or off, selecting an effort level, or setting a token budget. A model may support more than one of these at the same time. Present only when reasoning is supported."
    input_modalities: list[Modality]
    "Input types the model accepts, such as text, image, or audio."
    output_modalities: list[Modality]
    "Output types the model can produce, such as text or image."
    interleaved: Interleaved
    "`false` means reasoning stays in `content` and cannot be separated. A string (`reasoning_content` or `reasoning_details`) means the model can parse reasoning into a top-level field of that name via `parse_reasoning`."
    base_model: Nullable[str]
    "Canonical model identifier from models.dev (e.g. `zhipuai/glm-5.2`)."
    mode: Mode
    "Primary API endpoint type for this model.\n\n    ``chat`` routes requests to ``/v1/chat/completions``,\n    ``completion`` to ``/v1/completions``, and\n    ``embedding`` to ``/v1/embeddings``.\n    "
    default_params: Nullable[DefaultSamplingParams]
    "Default sampling parameters applied at inference time when the request does not specify them."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            if val != UNSET_SENTINEL:
                m[k] = val
        return m
