"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Literal

Mode = Literal["chat", "completion", "embedding"]
"Primary API endpoint type for this model.\n\n``chat`` routes requests to ``/v1/chat/completions``,\n``completion`` to ``/v1/completions``, and\n``embedding`` to ``/v1/embeddings``.\n"
