"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Literal

import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import BaseModel
from friendli.core.utils import validate_const


class ReasoningToggleTypedDict(TypedDict):
    """Reasoning can be turned on or off."""

    type: Literal["toggle"]


class ReasoningToggle(BaseModel):
    """Reasoning can be turned on or off."""

    TYPE: Annotated[
        Annotated[Literal["toggle"], AfterValidator(validate_const("toggle"))],
        pydantic.Field(alias="type"),
    ] = "toggle"


try:
    ReasoningToggle.model_rebuild()
except NameError:
    pass
