"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .responsestextformatjsonobject import (
    ResponsesTextFormatJSONObject,
    ResponsesTextFormatJSONObjectTypedDict,
)
from .responsestextformatjsonschema import (
    ResponsesTextFormatJSONSchema,
    ResponsesTextFormatJSONSchemaTypedDict,
)
from .responsestextformattext import (
    ResponsesTextFormatText,
    ResponsesTextFormatTextTypedDict,
)

ResponsesTextFormatTypedDict = TypeAliasType(
    "ResponsesTextFormatTypedDict",
    ResponsesTextFormatTextTypedDict
    | ResponsesTextFormatJSONObjectTypedDict
    | ResponsesTextFormatJSONSchemaTypedDict,
)
ResponsesTextFormat = Annotated[
    ResponsesTextFormatJSONObject
    | ResponsesTextFormatJSONSchema
    | ResponsesTextFormatText,
    Field(discriminator="TYPE"),
]
