"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsesoutputtext import ResponsesOutputText, ResponsesOutputTextTypedDict
from friendli.core.types import BaseModel
from friendli.core.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, TypedDict

ResponsesOutputMessageStatus = Literal["in_progress", "completed", "incomplete"]
"The status of the message. One of `in_progress`, `completed`, or `incomplete`."


class ResponsesOutputMessageTypedDict(TypedDict):
    id: str
    "The unique ID of the output message."
    status: ResponsesOutputMessageStatus
    "The status of the message. One of `in_progress`, `completed`, or `incomplete`."
    content: List[ResponsesOutputTextTypedDict]
    "The content of the output message."
    type: Literal["message"]
    "The type of the output message. Always `message`."
    role: Literal["assistant"]
    "The role of the output message. Always `assistant`."


class ResponsesOutputMessage(BaseModel):
    id: str
    "The unique ID of the output message."
    status: ResponsesOutputMessageStatus
    "The status of the message. One of `in_progress`, `completed`, or `incomplete`."
    content: List[ResponsesOutputText]
    "The content of the output message."
    TYPE: Annotated[
        Annotated[Literal["message"], AfterValidator(validate_const("message"))],
        pydantic.Field(alias="type"),
    ] = "message"
    "The type of the output message. Always `message`."
    ROLE: Annotated[
        Annotated[Literal["assistant"], AfterValidator(validate_const("assistant"))],
        pydantic.Field(alias="role"),
    ] = "assistant"
    "The role of the output message. Always `assistant`."


try:
    ResponsesOutputMessage.model_rebuild()
except NameError:
    pass
