"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Literal, NotRequired

import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import (
    UNSET,
    UNSET_SENTINEL,
    BaseModel,
    Nullable,
    OptionalNullable,
)
from friendli.core.utils import validate_const


class ResponsesCustomToolTypedDict(TypedDict):
    name: str
    "The name of the custom tool, used to identify it in tool calls."
    type: Literal["custom"]
    "The type of the custom tool. Always `custom`."
    description: NotRequired[Nullable[str]]
    "Optional description of the custom tool, used to provide more context."


class ResponsesCustomTool(BaseModel):
    name: str
    "The name of the custom tool, used to identify it in tool calls."
    TYPE: Annotated[
        Annotated[Literal["custom"], AfterValidator(validate_const("custom"))],
        pydantic.Field(alias="type"),
    ] = "custom"
    "The type of the custom tool. Always `custom`."
    description: OptionalNullable[str] = UNSET
    "Optional description of the custom tool, used to provide more context."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    ResponsesCustomTool.model_rebuild()
except NameError:
    pass
