"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .responsescustomtool import ResponsesCustomTool, ResponsesCustomToolTypedDict
from .responsesfunctiontool import ResponsesFunctionTool, ResponsesFunctionToolTypedDict

ResponsesToolTypedDict = TypeAliasType(
    "ResponsesToolTypedDict",
    ResponsesCustomToolTypedDict | ResponsesFunctionToolTypedDict,
)
ResponsesTool = Annotated[
    ResponsesCustomTool | ResponsesFunctionTool, Field(discriminator="TYPE")
]
