"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, NotRequired

import pydantic
from pydantic import SerializeAsAny, model_serializer
from typing_extensions import TypedDict

from friendli.core.types import (
    UNSET,
    UNSET_SENTINEL,
    BaseModel,
    Nullable,
    OptionalNullable,
)

from .responsestextformat import ResponsesTextFormat, ResponsesTextFormatTypedDict


class ResponsesTextConfigTypedDict(TypedDict):
    format_: NotRequired[Nullable[ResponsesTextFormatTypedDict]]
    'An object specifying the format that the model must output. Configuring `{ \\"type\\": \\"json_schema\\" }` enables Structured Outputs. The default format is `{ \\"type\\": \\"text\\" }`.'


class ResponsesTextConfig(BaseModel):
    format_: Annotated[
        SerializeAsAny[OptionalNullable[ResponsesTextFormat]],
        pydantic.Field(alias="format"),
    ] = UNSET
    'An object specifying the format that the model must output. Configuring `{ \\"type\\": \\"json_schema\\" }` enables Structured Outputs. The default format is `{ \\"type\\": \\"text\\" }`.'

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["format"])
        nullable_fields = set(["format"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    ResponsesTextConfig.model_rebuild()
except NameError:
    pass
