"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsesfunctioncall import ResponsesFunctionCall, ResponsesFunctionCallTypedDict
from .responsesoutputmessage import (
    ResponsesOutputMessage,
    ResponsesOutputMessageTypedDict,
)
from .responsesreasoningitem import (
    ResponsesReasoningItem,
    ResponsesReasoningItemTypedDict,
)
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType

ResponsesOutputItemTypedDict = TypeAliasType(
    "ResponsesOutputItemTypedDict",
    Union[
        ResponsesOutputMessageTypedDict,
        ResponsesReasoningItemTypedDict,
        ResponsesFunctionCallTypedDict,
    ],
)
ResponsesOutputItem = Annotated[
    Union[ResponsesFunctionCall, ResponsesOutputMessage, ResponsesReasoningItem],
    Field(discriminator="TYPE"),
]
