"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from friendli.core.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ResponsesStreamFunctionCallArgumentsDeltaTypedDict(TypedDict):
    item_id: str
    "The ID of the output item."
    output_index: int
    "The index of the output item."
    delta: str
    "The function-call arguments delta that is added."
    sequence_number: int
    "The sequence number for this event."
    type: Literal["response.function_call_arguments.delta"]
    "The type of the event."


class ResponsesStreamFunctionCallArgumentsDelta(BaseModel):
    item_id: str
    "The ID of the output item."
    output_index: int
    "The index of the output item."
    delta: str
    "The function-call arguments delta that is added."
    sequence_number: int
    "The sequence number for this event."
    TYPE: Annotated[
        Annotated[
            Literal["response.function_call_arguments.delta"],
            AfterValidator(validate_const("response.function_call_arguments.delta")),
        ],
        pydantic.Field(alias="type"),
    ] = "response.function_call_arguments.delta"
    "The type of the event."


try:
    ResponsesStreamFunctionCallArgumentsDelta.model_rebuild()
except NameError:
    pass
