"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Discriminator, Tag
from typing_extensions import TypeAliasType

from friendli.core.utils import get_discriminator

from .responsesoutputtext import ResponsesOutputText, ResponsesOutputTextTypedDict
from .responsesreasoningtext import (
    ResponsesReasoningText,
    ResponsesReasoningTextTypedDict,
)

ResponsesContentPartTypedDict = TypeAliasType(
    "ResponsesContentPartTypedDict",
    ResponsesOutputTextTypedDict | ResponsesReasoningTextTypedDict,
)
ResponsesContentPart = Annotated[
    Annotated[ResponsesOutputText, Tag("output_text")]
    | Annotated[ResponsesReasoningText, Tag("reasoning_text")],
    Discriminator(lambda m: get_discriminator(m, "type", "type")),
]
