"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsestextformatjsonobject import (
    ResponsesTextFormatJSONObject,
    ResponsesTextFormatJSONObjectTypedDict,
)
from .responsestextformatjsonschema import (
    ResponsesTextFormatJSONSchema,
    ResponsesTextFormatJSONSchemaTypedDict,
)
from .responsestextformattext import (
    ResponsesTextFormatText,
    ResponsesTextFormatTextTypedDict,
)
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType

ResponsesTextFormatTypedDict = TypeAliasType(
    "ResponsesTextFormatTypedDict",
    Union[
        ResponsesTextFormatTextTypedDict,
        ResponsesTextFormatJSONObjectTypedDict,
        ResponsesTextFormatJSONSchemaTypedDict,
    ],
)
ResponsesTextFormat = Annotated[
    Union[
        ResponsesTextFormatJSONObject,
        ResponsesTextFormatJSONSchema,
        ResponsesTextFormatText,
    ],
    Field(discriminator="TYPE"),
]
