"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from friendli.core.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ResponsesTextFormatTextTypedDict(TypedDict):
    type: Literal["text"]
    "The type of response format being defined. Always `text`."


class ResponsesTextFormatText(BaseModel):
    TYPE: Annotated[
        Annotated[Literal["text"], AfterValidator(validate_const("text"))],
        pydantic.Field(alias="type"),
    ] = "text"
    "The type of response format being defined. Always `text`."


try:
    ResponsesTextFormatText.model_rebuild()
except NameError:
    pass
