"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Literal

import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import BaseModel
from friendli.core.utils import validate_const


class ResponsesTextFormatJSONObjectTypedDict(TypedDict):
    type: Literal["json_object"]
    "The type of response format being defined. Always `json_object`."


class ResponsesTextFormatJSONObject(BaseModel):
    TYPE: Annotated[
        Annotated[
            Literal["json_object"], AfterValidator(validate_const("json_object"))
        ],
        pydantic.Field(alias="type"),
    ] = "json_object"
    "The type of response format being defined. Always `json_object`."


try:
    ResponsesTextFormatJSONObject.model_rebuild()
except NameError:
    pass
