"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .responsesinputimage import ResponsesInputImage, ResponsesInputImageTypedDict
from .responsesinputtext import ResponsesInputText, ResponsesInputTextTypedDict
from .responsesoutputtext import ResponsesOutputText, ResponsesOutputTextTypedDict
from .responsesrefusal import ResponsesRefusal, ResponsesRefusalTypedDict

ResponsesContentBlockTypedDict = TypeAliasType(
    "ResponsesContentBlockTypedDict",
    ResponsesInputTextTypedDict
    | ResponsesInputImageTypedDict
    | ResponsesOutputTextTypedDict
    | ResponsesRefusalTypedDict,
)
ResponsesContentBlock = Annotated[
    ResponsesInputImage | ResponsesInputText | ResponsesOutputText | ResponsesRefusal,
    Field(discriminator="TYPE"),
]
