"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from friendli.core.types import BaseModel


class ResponsesInputTokensDetailsTypedDict(TypedDict):
    cached_tokens: int
    "The number of tokens that were retrieved from the cache."


class ResponsesInputTokensDetails(BaseModel):
    cached_tokens: int
    "The number of tokens that were retrieved from the cache."
