"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Literal

import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import BaseModel
from friendli.core.utils import validate_const

from .responsesoutputitem import ResponsesOutputItem, ResponsesOutputItemTypedDict


class ResponsesStreamOutputItemDoneTypedDict(TypedDict):
    output_index: int
    "The index of the output item that was marked done."
    item: ResponsesOutputItemTypedDict
    sequence_number: int
    "The sequence number for this event."
    type: Literal["response.output_item.done"]
    "The type of the event."


class ResponsesStreamOutputItemDone(BaseModel):
    output_index: int
    "The index of the output item that was marked done."
    item: ResponsesOutputItem
    sequence_number: int
    "The sequence number for this event."
    TYPE: Annotated[
        Annotated[
            Literal["response.output_item.done"],
            AfterValidator(validate_const("response.output_item.done")),
        ],
        pydantic.Field(alias="type"),
    ] = "response.output_item.done"
    "The type of the event."


try:
    ResponsesStreamOutputItemDone.model_rebuild()
except NameError:
    pass
