"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsesfunctioncalloutputcontent import (
    ResponsesFunctionCallOutputContent,
    ResponsesFunctionCallOutputContentTypedDict,
)
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict

ResponsesFunctionCallOutputOutputTypedDict = TypeAliasType(
    "ResponsesFunctionCallOutputOutputTypedDict",
    Union[str, List[ResponsesFunctionCallOutputContentTypedDict]],
)
"Text or image output of the function tool call. Can be a JSON string of the output, or an array of content parts (text or image)."
ResponsesFunctionCallOutputOutput = TypeAliasType(
    "ResponsesFunctionCallOutputOutput",
    Union[str, List[ResponsesFunctionCallOutputContent]],
)
"Text or image output of the function tool call. Can be a JSON string of the output, or an array of content parts (text or image)."
ResponsesFunctionCallOutputStatus = Literal["in_progress", "completed", "incomplete"]


class ResponsesFunctionCallOutputTypedDict(TypedDict):
    call_id: str
    "The unique ID of the function tool call generated by the model."
    output: ResponsesFunctionCallOutputOutputTypedDict
    "Text or image output of the function tool call. Can be a JSON string of the output, or an array of content parts (text or image)."
    type: Literal["function_call_output"]
    "The type of the function tool call output. Always `function_call_output`."
    id: NotRequired[Nullable[str]]
    "The unique ID of the function tool call output."
    status: NotRequired[Nullable[ResponsesFunctionCallOutputStatus]]
    "The status of the item. One of `in_progress`, `completed`, or `incomplete`."


class ResponsesFunctionCallOutput(BaseModel):
    call_id: str
    "The unique ID of the function tool call generated by the model."
    output: ResponsesFunctionCallOutputOutput
    "Text or image output of the function tool call. Can be a JSON string of the output, or an array of content parts (text or image)."
    TYPE: Annotated[
        Annotated[
            Literal["function_call_output"],
            AfterValidator(validate_const("function_call_output")),
        ],
        pydantic.Field(alias="type"),
    ] = "function_call_output"
    "The type of the function tool call output. Always `function_call_output`."
    id: OptionalNullable[str] = UNSET
    "The unique ID of the function tool call output."
    status: OptionalNullable[ResponsesFunctionCallOutputStatus] = UNSET
    "The status of the item. One of `in_progress`, `completed`, or `incomplete`."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "status"])
        nullable_fields = set(["id", "status"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    ResponsesFunctionCallOutput.model_rebuild()
except NameError:
    pass
