"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Literal

import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import BaseModel
from friendli.core.utils import validate_const


class ResponsesRefusalTypedDict(TypedDict):
    refusal: str
    "The refusal explanation from the model."
    type: Literal["refusal"]
    "The type of the refusal. Always `refusal`."


class ResponsesRefusal(BaseModel):
    refusal: str
    "The refusal explanation from the model."
    TYPE: Annotated[
        Annotated[Literal["refusal"], AfterValidator(validate_const("refusal"))],
        pydantic.Field(alias="type"),
    ] = "refusal"
    "The type of the refusal. Always `refusal`."


try:
    ResponsesRefusal.model_rebuild()
except NameError:
    pass
