"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsesinputimage import ResponsesInputImage, ResponsesInputImageTypedDict
from .responsesinputtext import ResponsesInputText, ResponsesInputTextTypedDict
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType

ResponsesCustomToolCallOutputContentTypedDict = TypeAliasType(
    "ResponsesCustomToolCallOutputContentTypedDict",
    Union[ResponsesInputTextTypedDict, ResponsesInputImageTypedDict],
)
ResponsesCustomToolCallOutputContent = Annotated[
    Union[ResponsesInputImage, ResponsesInputText], Field(discriminator="TYPE")
]
