"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from typing_extensions import TypedDict


class ResponsesOutputTokensDetailsTypedDict(TypedDict):
    reasoning_tokens: int
    "The number of reasoning tokens."


class ResponsesOutputTokensDetails(BaseModel):
    reasoning_tokens: int
    "The number of reasoning tokens."
