"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Literal

import pydantic
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypedDict

from friendli.core.types import BaseModel
from friendli.core.utils import validate_const


class ResponsesInputImageTypedDict(TypedDict):
    image_url: str
    "The URL of the image to be sent to the model. A fully qualified URL or base64 encoded image in a data URL."
    type: Literal["input_image"]
    "The type of the input item. Always `input_image`."


class ResponsesInputImage(BaseModel):
    image_url: str
    "The URL of the image to be sent to the model. A fully qualified URL or base64 encoded image in a data URL."
    TYPE: Annotated[
        Annotated[
            Literal["input_image"], AfterValidator(validate_const("input_image"))
        ],
        pydantic.Field(alias="type"),
    ] = "input_image"
    "The type of the input item. Always `input_image`."


try:
    ResponsesInputImage.model_rebuild()
except NameError:
    pass
