"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsessuccess import ResponsesSuccess, ResponsesSuccessTypedDict
from friendli.core.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict

ResponsesStreamResponseEventType = Literal[
    "response.created",
    "response.in_progress",
    "response.completed",
    "response.incomplete",
    "response.failed",
]
"The type of the event."


class ResponsesStreamResponseEventTypedDict(TypedDict):
    type: ResponsesStreamResponseEventType
    "The type of the event."
    response: ResponsesSuccessTypedDict
    sequence_number: int
    "The sequence number for this event."


class ResponsesStreamResponseEvent(BaseModel):
    type: ResponsesStreamResponseEventType
    "The type of the event."
    response: ResponsesSuccess
    sequence_number: int
    "The sequence number for this event."
