"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsesinputimage import ResponsesInputImage, ResponsesInputImageTypedDict
from .responsesinputtext import ResponsesInputText, ResponsesInputTextTypedDict
from .responsesoutputtext import ResponsesOutputText, ResponsesOutputTextTypedDict
from .responsesrefusal import ResponsesRefusal, ResponsesRefusalTypedDict
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType

ResponsesContentBlockTypedDict = TypeAliasType(
    "ResponsesContentBlockTypedDict",
    Union[
        ResponsesInputTextTypedDict,
        ResponsesInputImageTypedDict,
        ResponsesOutputTextTypedDict,
        ResponsesRefusalTypedDict,
    ],
)
ResponsesContentBlock = Annotated[
    Union[
        ResponsesInputImage, ResponsesInputText, ResponsesOutputText, ResponsesRefusal
    ],
    Field(discriminator="TYPE"),
]
