"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsesoutputitem import ResponsesOutputItem, ResponsesOutputItemTypedDict
from friendli.core.types import BaseModel
from friendli.core.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ResponsesStreamOutputItemAddedTypedDict(TypedDict):
    output_index: int
    "The index of the output item that was added."
    item: ResponsesOutputItemTypedDict
    sequence_number: int
    "The sequence number for this event."
    type: Literal["response.output_item.added"]
    "The type of the event."


class ResponsesStreamOutputItemAdded(BaseModel):
    output_index: int
    "The index of the output item that was added."
    item: ResponsesOutputItem
    sequence_number: int
    "The sequence number for this event."
    TYPE: Annotated[
        Annotated[
            Literal["response.output_item.added"],
            AfterValidator(validate_const("response.output_item.added")),
        ],
        pydantic.Field(alias="type"),
    ] = "response.output_item.added"
    "The type of the event."


try:
    ResponsesStreamOutputItemAdded.model_rebuild()
except NameError:
    pass
