"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class ResponsesCustomToolCallTypedDict(TypedDict):
    call_id: str
    "An identifier used to map this custom tool call to a tool call output."
    name: str
    "The name of the custom tool being called."
    input: str
    "The input for the custom tool call generated by the model."
    type: Literal["custom_tool_call"]
    "The type of the custom tool call. Always `custom_tool_call`."
    id: NotRequired[Nullable[str]]
    "The unique ID of the custom tool call."


class ResponsesCustomToolCall(BaseModel):
    call_id: str
    "An identifier used to map this custom tool call to a tool call output."
    name: str
    "The name of the custom tool being called."
    input: str
    "The input for the custom tool call generated by the model."
    TYPE: Annotated[
        Annotated[
            Literal["custom_tool_call"],
            AfterValidator(validate_const("custom_tool_call")),
        ],
        pydantic.Field(alias="type"),
    ] = "custom_tool_call"
    "The type of the custom tool call. Always `custom_tool_call`."
    id: OptionalNullable[str] = UNSET
    "The unique ID of the custom tool call."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id"])
        nullable_fields = set(["id"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    ResponsesCustomToolCall.model_rebuild()
except NameError:
    pass
