"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .responsescustomtool import ResponsesCustomTool, ResponsesCustomToolTypedDict
from .responsesfunctiontool import ResponsesFunctionTool, ResponsesFunctionToolTypedDict
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType

ResponsesToolTypedDict = TypeAliasType(
    "ResponsesToolTypedDict",
    Union[ResponsesCustomToolTypedDict, ResponsesFunctionToolTypedDict],
)
ResponsesTool = Annotated[
    Union[ResponsesCustomTool, ResponsesFunctionTool], Field(discriminator="TYPE")
]
