"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Literal

from typing_extensions import TypedDict

from friendli.core.types import BaseModel

Code = Literal[
    "server_error",
    "rate_limit_exceeded",
    "invalid_prompt",
    "vector_store_timeout",
    "invalid_image",
    "invalid_image_format",
    "invalid_base64_image",
    "invalid_image_url",
    "image_too_large",
    "image_too_small",
    "image_parse_error",
    "image_content_policy_violation",
    "invalid_image_mode",
    "image_file_too_large",
    "unsupported_image_media_type",
    "empty_image_file",
    "failed_to_download_image",
    "image_file_not_found",
]
"The error code for the response."


class ResponsesErrorTypedDict(TypedDict):
    code: Code
    "The error code for the response."
    message: str
    "A human-readable description of the error."


class ResponsesError(BaseModel):
    code: Code
    "The error code for the response."
    message: str
    "A human-readable description of the error."
