"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from friendli.core.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ResponsesInputTextTypedDict(TypedDict):
    text: str
    "The text input to the model."
    type: Literal["input_text"]
    "The type of the input item. Always `input_text`."


class ResponsesInputText(BaseModel):
    text: str
    "The text input to the model."
    TYPE: Annotated[
        Annotated[Literal["input_text"], AfterValidator(validate_const("input_text"))],
        pydantic.Field(alias="type"),
    ] = "input_text"
    "The type of the input item. Always `input_text`."


try:
    ResponsesInputText.model_rebuild()
except NameError:
    pass
