"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, List, Literal, Union

import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing_extensions import TypeAliasType, TypedDict

from friendli.core.types import UNSET_SENTINEL, BaseModel, Nullable, OptionalNullable
from friendli.core.utils import validate_const

from .responsescontentblock import ResponsesContentBlock, ResponsesContentBlockTypedDict

ResponsesInputMessageRole = Literal["user", "assistant", "system", "developer"]
"The role of the message input. One of `user`, `assistant`, `system`, or `developer`."
ResponsesInputMessageContentTypedDict = TypeAliasType(
    "ResponsesInputMessageContentTypedDict", str | list[ResponsesContentBlockTypedDict]
)
"Text or image input to the model. Can also contain previous assistant responses."
ResponsesInputMessageContent = TypeAliasType(
    "ResponsesInputMessageContent", str | list[ResponsesContentBlock]
)
"Text or image input to the model. Can also contain previous assistant responses."


class ResponsesInputMessageTypedDict(TypedDict):
    role: ResponsesInputMessageRole
    "The role of the message input. One of `user`, `assistant`, `system`, or `developer`."
    content: ResponsesInputMessageContentTypedDict
    "Text or image input to the model. Can also contain previous assistant responses."
    type: Nullable[Literal["message"]]
    "The type of the message input. Always `message`."


class ResponsesInputMessage(BaseModel):
    role: ResponsesInputMessageRole
    "The role of the message input. One of `user`, `assistant`, `system`, or `developer`."
    content: ResponsesInputMessageContent
    "Text or image input to the model. Can also contain previous assistant responses."
    TYPE: Annotated[
        Annotated[
            OptionalNullable[Literal["message"]],
            AfterValidator(validate_const("message")),
        ],
        pydantic.Field(alias="type"),
    ] = "message"
    "The type of the message input. Always `message`."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        nullable_fields = set(["type"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    ResponsesInputMessage.model_rebuild()
except NameError:
    pass
