"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from friendli.core.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class ResponsesStreamOutputTextDeltaTypedDict(TypedDict):
    item_id: str
    "The ID of the output item."
    output_index: int
    "The index of the output item."
    content_index: int
    "The index of the content part within the output item."
    delta: str
    "The text delta that was added."
    sequence_number: int
    "The sequence number for this event."
    type: Literal["response.output_text.delta"]
    "The type of the event."


class ResponsesStreamOutputTextDelta(BaseModel):
    item_id: str
    "The ID of the output item."
    output_index: int
    "The index of the output item."
    content_index: int
    "The index of the content part within the output item."
    delta: str
    "The text delta that was added."
    sequence_number: int
    "The sequence number for this event."
    TYPE: Annotated[
        Annotated[
            Literal["response.output_text.delta"],
            AfterValidator(validate_const("response.output_text.delta")),
        ],
        pydantic.Field(alias="type"),
    ] = "response.output_text.delta"
    "The type of the event."


try:
    ResponsesStreamOutputTextDelta.model_rebuild()
except NameError:
    pass
