"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, NotRequired, Optional

from pydantic import model_serializer
from typing_extensions import TypedDict

from friendli.core.types import UNSET_SENTINEL, BaseModel
from friendli.core.utils import FieldMetadata, SecurityMetadata


class SecurityTypedDict(TypedDict):
    token: NotRequired[str]


class Security(BaseModel):
    token: Annotated[
        str | None,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["token"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        return m
