"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class ServerVadChunkingStrategyTypedDict(TypedDict):
    type: Literal["server_vad"]
    "Must be set to `server_vad` to enable manual chunking using server side VAD."
    prefix_padding_ms: NotRequired[Nullable[int]]
    "Amount of audio to include before the VAD detected speech (in milliseconds)."
    silence_duration_ms: NotRequired[Nullable[int]]
    "Duration of silence to detect speech stop (in milliseconds). With shorter values the model will respond more quickly, but may jump in on short pauses from the user."
    threshold: NotRequired[Nullable[float]]
    "Sensitivity threshold (0.0 to 1.0) for voice activity detection. A higher threshold will require louder audio to activate the model, and thus might perform better in noisy environments."


class ServerVadChunkingStrategy(BaseModel):
    TYPE: Annotated[
        Annotated[Literal["server_vad"], AfterValidator(validate_const("server_vad"))],
        pydantic.Field(alias="type"),
    ] = "server_vad"
    "Must be set to `server_vad` to enable manual chunking using server side VAD."
    prefix_padding_ms: OptionalNullable[int] = UNSET
    "Amount of audio to include before the VAD detected speech (in milliseconds)."
    silence_duration_ms: OptionalNullable[int] = UNSET
    "Duration of silence to detect speech stop (in milliseconds). With shorter values the model will respond more quickly, but may jump in on short pauses from the user."
    threshold: OptionalNullable[float] = UNSET
    "Sensitivity threshold (0.0 to 1.0) for voice activity detection. A higher threshold will require louder audio to activate the model, and thus might perform better in noisy environments."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["prefix_padding_ms", "silence_duration_ms", "threshold"])
        nullable_fields = set(["prefix_padding_ms", "silence_duration_ms", "threshold"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    ServerVadChunkingStrategy.model_rebuild()
except NameError:
    pass
