"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import List

from typing_extensions import TypedDict

from friendli.core.types import BaseModel

from .modelcatalogresponseitem import (
    ModelCatalogResponseItem,
    ModelCatalogResponseItemTypedDict,
)


class ServerlessModelListSuccessTypedDict(TypedDict):
    """`/v1/models` API response."""

    data: list[ModelCatalogResponseItemTypedDict]


class ServerlessModelListSuccess(BaseModel):
    """`/v1/models` API response."""

    data: list[ModelCatalogResponseItem]
