"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class StreamOptionsTypedDict(TypedDict):
    include_usage: NotRequired[Nullable[bool]]
    'When set to `true`,\n    the number of tokens used will be included at the end of the stream result in the form of\n    `\\"usage\\": {\\"completion_tokens\\": number, \\"prompt_tokens\\": number, \\"total_tokens\\": number}`.\n\n    '


class StreamOptions(BaseModel):
    include_usage: OptionalNullable[bool] = UNSET
    'When set to `true`,\n    the number of tokens used will be included at the end of the stream result in the form of\n    `\\"usage\\": {\\"completion_tokens\\": number, \\"prompt_tokens\\": number, \\"total_tokens\\": number}`.\n\n    '

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["include_usage"])
        nullable_fields = set(["include_usage"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
