"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Literal, NotRequired

from pydantic import model_serializer
from typing_extensions import TypedDict

from friendli.core.types import (
    UNSET,
    UNSET_SENTINEL,
    BaseModel,
    Nullable,
    OptionalNullable,
)

from .audiotranscriptionusage import (
    AudioTranscriptionUsage,
    AudioTranscriptionUsageTypedDict,
)

StreamedAudioTranscriptionDataType = Literal[
    "transcript.text.delta", "transcript.text.done"
]
"The event type, which is `transcript.text.delta` or `transcript.text.done`."


class StreamedAudioTranscriptionDataTypedDict(TypedDict):
    type: StreamedAudioTranscriptionDataType
    "The event type, which is `transcript.text.delta` or `transcript.text.done`."
    delta: NotRequired[Nullable[str]]
    "The incremental transcript text."
    text: NotRequired[Nullable[str]]
    "The transcribed text."
    usage: NotRequired[Nullable[AudioTranscriptionUsageTypedDict]]


class StreamedAudioTranscriptionData(BaseModel):
    type: StreamedAudioTranscriptionDataType
    "The event type, which is `transcript.text.delta` or `transcript.text.done`."
    delta: OptionalNullable[str] = UNSET
    "The incremental transcript text."
    text: OptionalNullable[str] = UNSET
    "The transcribed text."
    usage: OptionalNullable[AudioTranscriptionUsage] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["delta", "text", "usage"])
        nullable_fields = set(["delta", "text", "usage"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
