"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .streamedtoolcallresult import (
    StreamedToolCallResult,
    StreamedToolCallResultTypedDict,
)
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class StreamedChatChoiceDeltaTypedDict(TypedDict):
    content: NotRequired[Nullable[str]]
    "The contents of the assistant message."
    role: NotRequired[Nullable[str]]
    "Role of the generated message author, in this case `assistant`."
    tool_calls: NotRequired[Nullable[List[StreamedToolCallResultTypedDict]]]


class StreamedChatChoiceDelta(BaseModel):
    content: OptionalNullable[str] = UNSET
    "The contents of the assistant message."
    role: OptionalNullable[str] = UNSET
    "Role of the generated message author, in this case `assistant`."
    tool_calls: OptionalNullable[List[StreamedToolCallResult]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["content", "role", "tool_calls"])
        nullable_fields = set(["content", "role", "tool_calls"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
