"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class StreamedFunctionResultTypedDict(TypedDict):
    arguments: str
    "The arguments for calling the function, generated by the model in JSON format.\n    Ensure to validate these arguments in your code before invoking the function since the model may not always produce valid JSON.\n    "
    name: NotRequired[Nullable[str]]
    "The name of the function to call."


class StreamedFunctionResult(BaseModel):
    arguments: str
    "The arguments for calling the function, generated by the model in JSON format.\n    Ensure to validate these arguments in your code before invoking the function since the model may not always produce valid JSON.\n    "
    name: OptionalNullable[str] = UNSET
    "The name of the function to call."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        nullable_fields = set(["name"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
