"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatusage import ChatUsage, ChatUsageTypedDict
from .streamedchatchoice import StreamedChatChoice, StreamedChatChoiceTypedDict
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class StreamedChatDataTypedDict(TypedDict):
    id: str
    "A unique ID of the chat completion."
    choices: List[StreamedChatChoiceTypedDict]
    created: int
    "The Unix timestamp (in seconds) for when the token is sampled."
    usage: NotRequired[Nullable[ChatUsageTypedDict]]
    object: Literal["chat.completion.chunk"]
    "The object type, which is always set to `chat.completion.chunk`."
    model: NotRequired[Nullable[str]]
    "The model to generate the completion. For dedicated endpoints, it returns the endpoint ID."


class StreamedChatData(BaseModel):
    id: str
    "A unique ID of the chat completion."
    choices: List[StreamedChatChoice]
    created: int
    "The Unix timestamp (in seconds) for when the token is sampled."
    usage: OptionalNullable[ChatUsage] = UNSET
    OBJECT: Annotated[
        Annotated[
            Literal["chat.completion.chunk"],
            AfterValidator(validate_const("chat.completion.chunk")),
        ],
        pydantic.Field(alias="object"),
    ] = "chat.completion.chunk"
    "The object type, which is always set to `chat.completion.chunk`."
    model: OptionalNullable[str] = UNSET
    "The model to generate the completion. For dedicated endpoints, it returns the endpoint ID."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["usage", "model"])
        nullable_fields = set(["usage", "model"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    StreamedChatData.model_rebuild()
except NameError:
    pass
