"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .streamedfunctionresult import (
    StreamedFunctionResult,
    StreamedFunctionResultTypedDict,
)
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class StreamedToolCallResultTypedDict(TypedDict):
    index: int
    "The index of tool call being generated."
    function: StreamedFunctionResultTypedDict
    type: Literal["function"]
    "The type of the tool."
    id: NotRequired[Nullable[str]]
    "The ID of the tool call."


class StreamedToolCallResult(BaseModel):
    index: int
    "The index of tool call being generated."
    function: StreamedFunctionResult
    TYPE: Annotated[
        Annotated[Literal["function"], AfterValidator(validate_const("function"))],
        pydantic.Field(alias="type"),
    ] = "function"
    "The type of the tool."
    id: OptionalNullable[str] = UNSET
    "The ID of the tool call."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id"])
        nullable_fields = set(["id"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    StreamedToolCallResult.model_rebuild()
except NameError:
    pass
