"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import BaseModel
from typing_extensions import TypedDict


class TextClassificationUsageTypedDict(TypedDict):
    prompt_tokens: int
    "Number of tokens in the input text."
    total_tokens: int
    "Total number of tokens used in the request."


class TextClassificationUsage(BaseModel):
    prompt_tokens: int
    "Number of tokens in the input text."
    total_tokens: int
    "Total number of tokens used in the request."
