"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from friendli.core.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class ToolMessageTypedDict(TypedDict):
    content: str
    "The content of tool message that contains the result of tool calling."
    tool_call_id: str
    "The ID of tool call corresponding to this message."
    role: Literal["tool"]
    "The role of the messages author."
    name: NotRequired[Nullable[str]]
    "An optional name of the tool call corresponding to this message."


class ToolMessage(BaseModel):
    content: str
    "The content of tool message that contains the result of tool calling."
    tool_call_id: str
    "The ID of tool call corresponding to this message."
    ROLE: Annotated[
        Annotated[Literal["tool"], AfterValidator(validate_const("tool"))],
        pydantic.Field(alias="role"),
    ] = "tool"
    "The role of the messages author."
    name: OptionalNullable[str] = UNSET
    "An optional name of the tool call corresponding to this message."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name"])
        nullable_fields = set(["name"])
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m


try:
    ToolMessage.model_rebuild()
except NameError:
    pass
