"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .producttype import ProductType
from friendli.core.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Dict
from typing_extensions import NotRequired, TypedDict


class UsageResultTypedDict(TypedDict):
    num_model_requests: int
    "The count of requests made."
    input_tokens: int
    "The aggregated number of input tokens used, including cached tokens."
    input_cached_tokens: int
    "The aggregated number of input tokens that has been cached."
    output_tokens: int
    "The aggregated number of text output tokens used."
    product_type: NotRequired[Nullable[ProductType]]
    "When `group_by=product_type`, this field provides the product type of the grouped usage result. Supported values are `model_apis` and `dedicated_endpoints`."
    model: NotRequired[Nullable[str]]
    "When `group_by=model`, this field provides the model ID of the grouped usage result. For Model APIs usage, this is the model ID. For Dedicated Endpoints usage, this is the endpoint ID."
    user_id: NotRequired[Nullable[str]]
    "When `group_by=user_id`, this field provides the user ID of the grouped usage result."
    gpu_usage: NotRequired[Nullable[Dict[str, int]]]
    "The GPU time in seconds, keyed by GPU type. Present when a bucket includes Dedicated Endpoints usage. When `group_by=user_id`, this is attributed to the bucket of the user who created the endpoint."
    processed_audio_length_ms: NotRequired[Nullable[int]]
    "The number of processed audio length in milliseconds. Present when bucket includes audio processing usage."


class UsageResult(BaseModel):
    num_model_requests: int
    "The count of requests made."
    input_tokens: int
    "The aggregated number of input tokens used, including cached tokens."
    input_cached_tokens: int
    "The aggregated number of input tokens that has been cached."
    output_tokens: int
    "The aggregated number of text output tokens used."
    product_type: OptionalNullable[ProductType] = UNSET
    "When `group_by=product_type`, this field provides the product type of the grouped usage result. Supported values are `model_apis` and `dedicated_endpoints`."
    model: OptionalNullable[str] = UNSET
    "When `group_by=model`, this field provides the model ID of the grouped usage result. For Model APIs usage, this is the model ID. For Dedicated Endpoints usage, this is the endpoint ID."
    user_id: OptionalNullable[str] = UNSET
    "When `group_by=user_id`, this field provides the user ID of the grouped usage result."
    gpu_usage: OptionalNullable[Dict[str, int]] = UNSET
    "The GPU time in seconds, keyed by GPU type. Present when a bucket includes Dedicated Endpoints usage. When `group_by=user_id`, this is attributed to the bucket of the user who created the endpoint."
    processed_audio_length_ms: OptionalNullable[int] = UNSET
    "The number of processed audio length in milliseconds. Present when bucket includes audio processing usage."

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "product_type",
                "model",
                "user_id",
                "gpu_usage",
                "processed_audio_length_ms",
            ]
        )
        nullable_fields = set(
            [
                "product_type",
                "model",
                "user_id",
                "gpu_usage",
                "processed_audio_length_ms",
            ]
        )
        serialized = handler(self)
        m = {}
        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields and self.__pydantic_fields_set__.intersection({n})
            )
            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val
        return m
