"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from datetime import datetime
from typing import List

from typing_extensions import TypedDict

from friendli.core.types import BaseModel

from .usageresult import UsageResult, UsageResultTypedDict


class UsageBucketTypedDict(TypedDict):
    """Usage bucket for a time window."""

    start_time: datetime
    end_time: datetime
    results: list[UsageResultTypedDict]


class UsageBucket(BaseModel):
    """Usage bucket for a time window."""

    start_time: datetime
    end_time: datetime
    results: list[UsageResult]
