"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Annotated, Union

from pydantic import Field
from typing_extensions import TypeAliasType

from .audiocontent import AudioContent, AudioContentTypedDict
from .imagecontent import ImageContent, ImageContentTypedDict
from .textcontent import TextContent, TextContentTypedDict
from .videocontent import VideoContent, VideoContentTypedDict

UserMessageContentMultiModalTypedDict = TypeAliasType(
    "UserMessageContentMultiModalTypedDict",
    TextContentTypedDict
    | AudioContentTypedDict
    | ImageContentTypedDict
    | VideoContentTypedDict,
)
UserMessageContentMultiModal = Annotated[
    AudioContent | ImageContent | TextContent | VideoContent,
    Field(discriminator="TYPE"),
]
