"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import List, Union

from typing_extensions import TypeAliasType, TypedDict

from friendli.core.types import BaseModel

LocTypedDict = TypeAliasType("LocTypedDict", str | int)
Loc = TypeAliasType("Loc", str | int)


class ValidationErrorTypedDict(TypedDict):
    loc: list[LocTypedDict]
    msg: str
    type: str


class ValidationError(BaseModel):
    loc: list[Loc]
    msg: str
    type: str
