"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import asyncio
from collections.abc import Callable
from typing import TYPE_CHECKING, Any, TypeVar

from .dynamic_imports import lazy_dir, lazy_getattr

_T = TypeVar("_T")


async def run_sync_in_thread(func: Callable[..., _T], *args) -> _T:
    """Run a synchronous function in a thread pool to avoid blocking the event loop."""
    return await asyncio.to_thread(func, *args)


if TYPE_CHECKING:
    from .annotations import get_discriminator
    from .datetimes import parse_datetime, parse_duration
    from .enums import OpenEnumMeta
    from .headers import get_headers, get_response_headers
    from .logger import Logger, get_body_content, get_default_logger
    from .metadata import (
        FieldMetadata,
        FormMetadata,
        HeaderMetadata,
        MultipartFormMetadata,
        PathParamMetadata,
        QueryParamMetadata,
        RequestMetadata,
        SecurityMetadata,
        find_metadata,
    )
    from .queryparams import get_query_params
    from .requestbodies import SerializedRequestBody, serialize_request_body
    from .retries import BackoffStrategy, Retries, RetryConfig, retry, retry_async
    from .security import get_security, get_security_from_env
    from .serializers import (
        get_pydantic_model,
        marshal_json,
        serialize_decimal,
        serialize_float,
        serialize_int,
        stream_to_bytes,
        stream_to_bytes_async,
        stream_to_text,
        stream_to_text_async,
        unmarshal,
        unmarshal_json,
        validate_const,
        validate_decimal,
        validate_float,
        validate_int,
    )
    from .url import generate_url, remove_suffix, template_url
    from .values import (
        cast_partial,
        get_global_from_env,
        match_content_type,
        match_response,
        match_status_codes,
    )
__all__ = [
    "BackoffStrategy",
    "FieldMetadata",
    "FormMetadata",
    "HeaderMetadata",
    "Logger",
    "MultipartFormMetadata",
    "OpenEnumMeta",
    "PathParamMetadata",
    "QueryParamMetadata",
    "RequestMetadata",
    "Retries",
    "RetryConfig",
    "SecurityMetadata",
    "SerializedRequestBody",
    "cast_partial",
    "find_metadata",
    "generate_url",
    "get_body_content",
    "get_default_logger",
    "get_discriminator",
    "get_global_from_env",
    "get_headers",
    "get_pydantic_model",
    "get_query_params",
    "get_response_headers",
    "get_security",
    "get_security_from_env",
    "marshal_json",
    "match_content_type",
    "match_response",
    "match_status_codes",
    "parse_datetime",
    "parse_duration",
    "remove_suffix",
    "retry",
    "retry_async",
    "serialize_decimal",
    "serialize_float",
    "serialize_int",
    "serialize_request_body",
    "stream_to_bytes",
    "stream_to_bytes_async",
    "stream_to_text",
    "stream_to_text_async",
    "template_url",
    "unmarshal",
    "unmarshal_json",
    "validate_const",
    "validate_decimal",
    "validate_float",
    "validate_int",
]
_dynamic_imports: dict[str, str] = {
    "BackoffStrategy": ".retries",
    "FieldMetadata": ".metadata",
    "find_metadata": ".metadata",
    "FormMetadata": ".metadata",
    "generate_url": ".url",
    "get_body_content": ".logger",
    "get_default_logger": ".logger",
    "get_discriminator": ".annotations",
    "parse_datetime": ".datetimes",
    "parse_duration": ".datetimes",
    "get_global_from_env": ".values",
    "get_headers": ".headers",
    "get_pydantic_model": ".serializers",
    "get_query_params": ".queryparams",
    "get_response_headers": ".headers",
    "get_security": ".security",
    "get_security_from_env": ".security",
    "HeaderMetadata": ".metadata",
    "Logger": ".logger",
    "marshal_json": ".serializers",
    "match_content_type": ".values",
    "match_status_codes": ".values",
    "match_response": ".values",
    "MultipartFormMetadata": ".metadata",
    "OpenEnumMeta": ".enums",
    "PathParamMetadata": ".metadata",
    "QueryParamMetadata": ".metadata",
    "remove_suffix": ".url",
    "Retries": ".retries",
    "retry": ".retries",
    "retry_async": ".retries",
    "RetryConfig": ".retries",
    "RequestMetadata": ".metadata",
    "SecurityMetadata": ".metadata",
    "serialize_decimal": ".serializers",
    "serialize_float": ".serializers",
    "serialize_int": ".serializers",
    "serialize_request_body": ".requestbodies",
    "SerializedRequestBody": ".requestbodies",
    "stream_to_text": ".serializers",
    "stream_to_text_async": ".serializers",
    "stream_to_bytes": ".serializers",
    "stream_to_bytes_async": ".serializers",
    "template_url": ".url",
    "unmarshal": ".serializers",
    "unmarshal_json": ".serializers",
    "validate_decimal": ".serializers",
    "validate_const": ".serializers",
    "validate_float": ".serializers",
    "validate_int": ".serializers",
    "cast_partial": ".values",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
