"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import enum
import sys
from typing import Any
from pydantic_core import core_schema


class OpenEnumMeta(enum.EnumMeta):
    if sys.version_info >= (3, 11):

        def __call__(
            cls,
            value,
            names=None,
            *values,
            module=None,
            qualname=None,
            type=None,
            start=1,
            boundary=None,
        ):
            if names is not None:
                return super().__call__(
                    value,
                    *values,
                    names=names,
                    module=module,
                    qualname=qualname,
                    type=type,
                    start=start,
                    boundary=boundary,
                )
            try:
                return super().__call__(
                    value,
                    *values,
                    names=names,
                    module=module,
                    qualname=qualname,
                    type=type,
                    start=start,
                    boundary=boundary,
                )
            except ValueError:
                return value
    else:

        def __call__(
            cls, value, names=None, *, module=None, qualname=None, type=None, start=1
        ):
            if names is not None:
                return super().__call__(
                    value,
                    names=names,
                    module=module,
                    qualname=qualname,
                    type=type,
                    start=start,
                )
            try:
                return super().__call__(
                    value,
                    names=names,
                    module=module,
                    qualname=qualname,
                    type=type,
                    start=start,
                )
            except ValueError:
                return value

    def __new__(mcs, name, bases, namespace, **kwargs):
        cls = super().__new__(mcs, name, bases, namespace, **kwargs)

        def __get_pydantic_core_schema__(
            cls_inner: Any, _source_type: Any, _handler: Any
        ) -> core_schema.CoreSchema:

            def validate_strict(v: Any) -> Any:
                if isinstance(v, cls_inner):
                    return v
                return enum.EnumMeta.__call__(cls_inner, v)

            def validate_lax(v: Any) -> Any:
                if isinstance(v, cls_inner):
                    return v
                try:
                    return enum.EnumMeta.__call__(cls_inner, v)
                except ValueError:
                    return v

            is_int_enum = False
            for base in cls_inner.__mro__:
                if base is int:
                    is_int_enum = True
                    break
                if base is str:
                    break
            base_schema = (
                core_schema.int_schema() if is_int_enum else core_schema.str_schema()
            )
            return core_schema.lax_or_strict_schema(
                lax_schema=core_schema.chain_schema(
                    [
                        base_schema,
                        core_schema.no_info_plain_validator_function(validate_lax),
                    ]
                ),
                strict_schema=core_schema.chain_schema(
                    [
                        base_schema,
                        core_schema.no_info_plain_validator_function(validate_strict),
                    ]
                ),
            )

        setattr(
            cls,
            "__get_pydantic_core_schema__",
            classmethod(__get_pydantic_core_schema__),
        )
        return cls
