workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Friendli-API-Schema:
        inputs:
            - location: registry.speakeasyapi.dev/friendliai/friendliai/friendli-api-schema
        transformations:
            - cleanup: true
targets:
    friendli_core:
        target: python
        source: Friendli-API-Schema
