workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Friendli-API-Schema:
        inputs:
            - location: registry.speakeasyapi.dev/friendliai/friendliai/friendli-api-schema
        registry:
            location: registry.speakeasyapi.dev/friendliai/friendliai/friendli-api-schema
targets:
    friendli:
        target: python
        source: Friendli-API-Schema
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/friendliai/friendliai/friendli-api-schema-code-samples
            blocking: false
