"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from friendli_core.types import BaseModel


class CreateDatasetRequestTypedDict(TypedDict):
    r"""Create dataset request."""

    name: str
    r"""Name of the dataset."""


class CreateDatasetRequest(BaseModel):
    r"""Create dataset request."""

    name: str
    r"""Name of the dataset."""
