"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

import pydantic
from typing_extensions import Annotated, TypedDict

from friendli_core.types import BaseModel


class DatasetInfoTypedDict(TypedDict):
    r"""Dataset info."""

    created_at: int
    r"""Unix timestamp (in seconds) of when the dataset was created."""
    id: str
    r"""ID of the dataset."""
    length: int
    r"""Number of samples."""
    name: str
    r"""Name of the dataset."""
    size: int
    r"""Size of the dataset in bytes."""
    updated_at: int
    r"""Unix timestamp (in seconds) of when the dataset was last modified."""


class DatasetInfo(BaseModel):
    r"""Dataset info."""

    created_at: Annotated[int, pydantic.Field(alias="createdAt")]
    r"""Unix timestamp (in seconds) of when the dataset was created."""

    id: str
    r"""ID of the dataset."""

    length: int
    r"""Number of samples."""

    name: str
    r"""Name of the dataset."""

    size: int
    r"""Size of the dataset in bytes."""

    updated_at: Annotated[int, pydantic.Field(alias="updatedAt")]
    r"""Unix timestamp (in seconds) of when the dataset was last modified."""
