name: Auto fix
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install ruff
        run: pip install ruff

      - name: Install sdk-transpiler
        run: pip install git+https://${{ secrets.BOT_TOKEN }}@github.com/friendliai/sdk-transpiler.git@main

      - name: Lint Python code blocks in md files
        run: python scripts/auto-fix.py

      - name: Transpile SDK to separate sync/async
        run: python -m sdk_transpiler -v src/friendli_core src/friendli_core

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto fix code styles and transpile sdk"
          branch: ${{ github.head_ref }}
          file_pattern: "."
          commit_options: "--no-verify"
